-- Generated by prepare_multiclub_isolation_fixture.py for staging only.
-- No schema changes, credential changes, email, deletion, or fixture resets.
begin;
do $seed$
declare
 f jsonb := $fixture$__FIXTURE_PAYLOAD__$fixture$::jsonb;
 actor_id uuid; actor_email text; club jsonb; player jsonb; game jsonb; roster jsonb;
 cid text; pid bigint; ids bigint[]; lineup bigint[]; result jsonb; saved jsonb;
 v_season_id uuid := (f->>'season_id')::uuid; draft jsonb; rev integer;
 meet public.pcs_interclub_meets; team_ids uuid[]; i integer; j integer; k integer;
 protected_before text; protected_after text;
begin
 perform pg_advisory_xact_lock(hashtextextended('pcs-fixture:'||(f->>'marker'),0));
 if f->>'project_ref'<>'sijpxjxvdtrehmqvirfi' or not exists (
  select 1 from public.clubs where id='tres_palapas' and features_json @> '{"staging_fixture":true,"synthetic_data_only":true}'
  and name='Tres Palapas — Staging Fixtures'
 ) then raise exception 'Isolated staging fixture guard failed'; end if;
 if (select count(*) from public.clubs where id in ('la-ribera-pickelball-club','cabo-test-club','la-paz-test-club')
      and features_json->>'isolation_fixture'=f->>'marker')=3 then
  raise notice 'Fixture already exists; preserving all manual testing changes'; return;
 end if;
 if exists(select 1 from public.players where club_id='la-ribera-pickelball-club')
  or exists(select 1 from public.clubs where id in ('cabo-test-club','la-paz-test-club'))
  or exists(select 1 from public.pcs_interclub_drafts where id=v_season_id) then
  raise exception 'Target clubs contain non-fixture data; refusing to replace them'; end if;
 select a.user_id,a.email into strict actor_id,actor_email
 from public.admin_role_assignments a join auth.users u on u.id=a.user_id and lower(u.email)=a.email
 join public.pcs_platform_admins pa on pa.user_id=u.id and pa.revoked_at is null
 where a.club_id='la-ribera-pickelball-club' and a.role='administrator' and a.revoked_at is null
 and (a.expires_at is null or a.expires_at>now()) and u.email_confirmed_at is not null;

 -- Preserve all existing Tres players, matches, leagues, tournaments and drafts.
 select md5(jsonb_build_array(
  (select jsonb_agg(to_jsonb(p) order by id) from players p where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(m) order by id) from matches m where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(l) order by id) from leagues_metadata l where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(t) order by id) from tournaments t where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(d) order by id) from pcs_interclub_drafts d where organizer_club_id='tres_palapas')
 )::text) into protected_before;

 -- Exercise normal club invitation creation and verified acceptance for both new clubs.
 draft := jsonb_set(jsonb_set(f->'draft','{club_ids}','["la-ribera-pickelball-club"]'),'{meets}','[]');
 saved := public.pcs_save_interclub_draft(actor_id,actor_email,'la-ribera-pickelball-club',v_season_id,0,draft);
 rev := (saved->>'revision')::integer;
 for club in select value from jsonb_array_elements(f->'clubs') loop
  cid := club->>'id';
  if cid<>'la-ribera-pickelball-club' then
   result := public.pcs_create_interclub_club_invitation(actor_id,actor_email,'la-ribera-pickelball-club',v_season_id,
    (club->>'invitation_id')::uuid,rev,draft,club->>'name',cid,actor_email);
   draft := result->'season'->'draft'; rev := (result->'season'->>'revision')::integer;
   result := public.pcs_interclub_club_invitation(p_action=>'accept',p_id=>(club->>'invitation_id')::uuid,
    p_actor_id=>actor_id,p_actor_email=>actor_email);
   if result->>'status'<>'accepted' then raise exception 'Club account was not accepted'; end if;
  end if;
  -- These synthetic clubs also need public pages for the club-link isolation checks.
  insert into public.pcs_platform_audit(actor_id,club_id,action,details)
  select actor_id,cid,'staging_isolation_fixture',jsonb_build_object('marker',f->>'marker','before',to_jsonb(c))
  from public.clubs c where id=cid;
  update public.clubs set is_active=true,status='active',plan_status='staging',onboarding_status='ready',
   primary_color=club->>'color',tagline=(club->>'code')||' synthetic test data — '||(f->>'marker'),
   support_email=lower(club->>'code')||'@multiclub.example.invalid',
   public_base_url='https://jupr-git-staging-pickleballattrespalapas1.vercel.app',
   features_json=features_json||jsonb_build_object('staging_fixture',true,'synthetic_data_only',true,'isolation_fixture',f->>'marker'),updated_at=now()
  where id=cid;

  ids := '{}';
  for player in select value from jsonb_array_elements(club->'players') loop
   insert into public.players(club_id,name,starting_rating,rating,wins,losses,matches_played,gender,active,last_game_at,last_game_at_v2,inactive_at,inactive_at_v2)
   values(cid,player->>'name',(player->>'starting_rating')::numeric,(player->>'rating')::numeric,
    (player->>'wins')::integer,(player->>'losses')::integer,(player->>'matches_played')::integer,player->>'gender',
    (player->>'active')::boolean,(player->>'last_game_at')::timestamptz,(player->>'last_game_at')::timestamptz,
    case when (player->>'active')::boolean then null else now() end,case when (player->>'active')::boolean then null else now() end)
   returning id into pid;
   ids := array_append(ids,pid);
   insert into public.player_profiles(club_id,player_id,preferred_channel,email)
   values(cid,pid,'email',player->>'email');
  end loop;

  insert into public.leagues_metadata(club_id,league_name,league_type,min_games,k_factor,is_active,status,description,started_at,rules_config,event_tags)
  values(cid,f->>'league','Individual',6,32,true,'active',(club->>'code')||' synthetic match history for club isolation testing',now(),
   '{"overview":{"league_format":"ladder"},"competition":{"scoring_profile":"standard_pickleball","match_structure":{"kind":"fixed_games","games":1,"result_counting":"each_game","completion":"all_games"},"standings_tiebreak":"wins_then_point_differential","playoff_format":"none"},"operation":{"session_mode":"scheduled_rounds","participation_mode":"flex","move_up_count":1,"move_down_count":1}}',
   jsonb_build_object('fixture',jsonb_build_array(f->>'marker'))),
  (cid,'Isolation Test Draft','Individual',6,32,false,'draft',(club->>'code')||' editable draft; should appear only in this club',null,
   '{"overview":{"league_format":"round_robin"},"operation":{"session_mode":"scheduled_rounds","participation_mode":"flex"}}',jsonb_build_object('fixture',jsonb_build_array(f->>'marker')));
  for i in 1..24 loop
   player := club->'players'->(i-1);
   insert into public.league_ratings(club_id,player_id,league_name,starting_rating,rating,wins,losses,matches_played,is_active)
   values(cid,ids[i],f->>'league',(player->>'starting_rating')::numeric,(player->>'rating')::numeric,
    (player->>'wins')::integer,(player->>'losses')::integer,(player->>'matches_played')::integer,(player->>'active')::boolean);
  end loop;
  for game in select value from jsonb_array_elements(club->'matches') loop
   insert into public.matches(club_id,date,league,t1_p1,t1_p2,t2_p1,t2_p2,score_t1,score_t2,
    t1_p1_r,t1_p2_r,t2_p1_r,t2_p2_r,t1_p1_r_end,t1_p2_r_end,t2_p1_r_end,t2_p2_r_end,elo_delta,elo_delta_t1,elo_delta_t2,
    match_type,match_format,context_type,context_id,week_tag,idempotency_key,notes)
   values(cid,(game->>0)::timestamptz,f->>'league',ids[(game->>1)::integer+1],ids[(game->>2)::integer+1],
    ids[(game->>3)::integer+1],ids[(game->>4)::integer+1],(game->>5)::integer,(game->>6)::integer,
    (game->>7)::numeric,(game->>8)::numeric,(game->>9)::numeric,(game->>10)::numeric,
    (game->>11)::numeric,(game->>12)::numeric,(game->>13)::numeric,(game->>14)::numeric,
    (game->>15)::numeric,(game->>15)::double precision,(game->>16)::double precision,
    'League','doubles','league',f->>'league',to_char((game->>0)::timestamptz,'IYYY-IW'),game->>17,f->>'marker');
  end loop;

  insert into public.tournaments(id,club_id,name,status,team_count,playoff_advance_count,playoff_best_of,start_date,end_date,event_tags)
  values((club->>'tournament_id')::uuid,cid,'Isolation Test Cup','DRAFT',4,4,1,
   (f->'draft'->>'start_date')::date,(f->'draft'->>'start_date')::date,jsonb_build_object('fixture',jsonb_build_array(f->>'marker')));
  insert into public.tournament_event_draws(id,tournament_id,name,status)
  values((club->>'draw_id')::uuid,(club->>'tournament_id')::uuid,'Mixed Doubles Test','draft');
  team_ids := '{}';
  for i in 0..3 loop
   team_ids := array_append(team_ids,(club->'team_ids'->>i)::uuid);
   insert into public.tournament_teams(id,tournament_id,club_id,draw_id,team_number,seed,player1_id,player2_id,source)
   values(team_ids[i+1],(club->>'tournament_id')::uuid,cid,(club->>'draw_id')::uuid,i+1,i+1,ids[13+i*2],ids[14+i*2],'manual');
  end loop;
  k := 0;
  for i in 1..3 loop
   for j in (i+1)..4 loop
    k := k+1;
    insert into public.tournament_games(tournament_id,club_id,draw_id,stage,rr_round_number,rr_slot_number,team_a_id,team_b_id,game_conflict_key)
    values((club->>'tournament_id')::uuid,cid,(club->>'draw_id')::uuid,'ROUND_ROBIN',k,1,team_ids[i],team_ids[j],
     (f->>'marker')||':'||cid||':rr:'||k::text);
   end loop;
  end loop;
 end loop;

 saved := public.pcs_save_interclub_draft(actor_id,actor_email,'la-ribera-pickelball-club',v_season_id,rev,f->'draft');
 perform public.pcs_open_interclub_meet_registration(actor_id,actor_email,'la-ribera-pickelball-club',v_season_id,
  (saved->>'revision')::integer,f->'draft'->'registration_rules');
 for club in select value from jsonb_array_elements(f->'clubs') loop
  cid := club->>'id';
  perform public.pcs_interclub_participation(actor_id,actor_email,cid,v_season_id,cid,1,'accept');
  select array_agg(p.id order by n.ordinality) into ids
  from jsonb_array_elements(club->'players') with ordinality n
  join public.players p on p.club_id=cid and p.name=n.value->>'name';
  for roster in select value from jsonb_array_elements(club->'rosters') loop
   select * into strict meet from public.pcs_interclub_meets m where m.season_id=v_season_id and m.plan_index=(roster->>'meet')::integer;
   select array_agg(ids[value::integer+1] order by ordinality) into lineup from jsonb_array_elements_text(roster->'slots') with ordinality;
   result := public.pcs_save_interclub_meet_roster(actor_id,actor_email,cid,v_season_id,meet.id,meet.revision,
    (roster->>'id')::uuid,0,(club->>'code')||' Test '||(roster->>'division'),roster->>'division',lineup);
   if result->'roster'->>'status'<>'eligible' then raise exception 'Fixture roster was not eligible: %',result->'roster'->'issues'; end if;
  end loop;
 end loop;
 select md5(jsonb_build_array(
  (select jsonb_agg(to_jsonb(p) order by id) from players p where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(m) order by id) from matches m where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(l) order by id) from leagues_metadata l where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(t) order by id) from tournaments t where club_id='tres_palapas'),
  (select jsonb_agg(to_jsonb(d) order by id) from pcs_interclub_drafts d where organizer_club_id='tres_palapas')
 )::text) into protected_after;
 if protected_after is distinct from protected_before then raise exception 'Existing Tres data changed; rolling back fixture'; end if;
end $seed$;
commit;
