insert into badges (badge_id, name, prestige, category, is_stackable, is_active, rarity, tier, icon_key, lore, hint, scope)
values
    ('participant', 'Participant', 10, 'Participation & Habit Loop', false, true, 'common', null, 'participant', 'Every career starts the same way: a name on the sheet and a moment on tape.', 'The archive doesn’t recognize potential. Only appearances.', 'overall'),
    ('dedicated_participant_50', 'Dedicated Participant', 25, 'Participation & Habit Loop', false, true, 'rare', null, 'dedicated_participant_50', 'Fifty matches is where routine becomes identity.', 'The schedule is starting to recognize you.', 'overall'),
    ('lifetime_participant_200', 'Lifetime Participant', 50, 'Participation & Habit Loop', false, true, 'epic', null, 'lifetime_participant_200', 'Two hundred matches doesn’t happen by accident. It happens by refusing to disappear.', 'The archive is getting heavy.', 'overall'),
    ('first_win', 'First Win', 15, 'Participation & Habit Loop', false, true, 'common', null, 'first_win', 'The first mark on the ledger. The tape starts rolling for real.', 'There is always a first frame on the reel.', 'overall'),
    ('weekly_regular', 'Weekly Regular', 35, 'Participation & Habit Loop', false, true, 'rare', null, 'weekly_regular', 'The schedule starts to recognize the face. The weeks keep stacking.', 'The calendar keeps calling.', 'league'),
    ('iron_week', 'Iron Week', 30, 'Participation & Habit Loop', true, true, 'common', null, 'iron_week', 'A week packed tight with tape. The grind leaves a signature.', 'Some weeks barely have room to breathe.', 'week'),
    ('marathon_month', 'Marathon Month', 60, 'Participation & Habit Loop', true, true, 'rare', null, 'marathon_month', 'A month that never slowed down. Every day kept its own clip.', 'The month is still writing.', 'month'),
    ('level_up', 'Level Up', 40, 'Skill Growth & Momentum', true, true, 'rare', null, 'level_up', 'Another rung claimed. The league notices the climb.', 'A new number appears on the nameplate.', 'league'),
    ('rocket_start', 'Rocket Start', 50, 'Skill Growth & Momentum', false, true, 'rare', null, 'rocket_start', 'The opening run shook the scoreboard. The room leaned in early.', 'The first stretch left a streak on the floor.', 'league'),
    ('most_improved_monthly', 'Most Improved', 55, 'Skill Growth & Momentum', true, true, 'epic', null, 'most_improved', 'A month where the climb couldn’t be ignored.', 'One month tilted harder than the rest.', 'month'),
    ('mountain_climber', 'Mountain Climber', 45, 'Skill Growth & Momentum', true, true, 'rare', null, 'mountain_climber', 'Ranks flipped. The ascent left landmarks.', 'The ladder looks different now.', 'league'),
    ('hot_streak', 'Hot Streak', 50, 'Skill Growth & Momentum', true, true, 'epic', null, 'hot_streak', 'Wins blur together on the tape. The run keeps rolling.', 'The film strip barely cools off.', 'league'),
    ('bounce_back', 'Bounce Back', 25, 'Skill Growth & Momentum', true, true, 'common', null, 'bounce_back', 'A stumble, then a reply. The echo lands clean.', 'The next frame told a different story.', 'match'),
    ('breakthrough', 'Breakthrough', 55, 'Skill Growth & Momentum', false, true, 'epic', null, 'breakthrough', 'The tape catches the moment the ceiling moves.', 'There was a game when things started to look different.', 'overall'),
    ('above_expectations', 'Above Expectations', 50, 'Skill Growth & Momentum', true, true, 'rare', null, 'above_expectations', 'The room expected one thing. The tape shows another.', 'The projection didn’t match the result.', 'overall'),
    ('ice_in_veins', 'Ice in Veins', 70, 'Clutch & Pressure', false, true, 'epic', null, 'ice_in_veins', 'When the margin tightened, the answer didn’t.', 'Cold hands don’t shake the camera.', 'overall'),
    ('clutch_performer', 'Clutch Performer', 60, 'Clutch & Pressure', false, true, 'rare', null, 'clutch_performer', 'Close frames keep leaning the same way.', 'The last points keep finding the same jersey.', 'overall'),
    ('pickle_perfection', 'Pickle Perfection', 75, 'Dominance & Quality', true, true, 'legendary', null, 'pickle_perfection', 'A shutout with no extra narration needed.', 'Sometimes the other side never shows up on the scoreboard.', 'match'),
    ('blowout_artist', 'Blowout Artist', 45, 'Dominance & Quality', true, true, 'rare', null, 'blowout_artist', 'The gap grew and never closed.', 'The margin kept widening.', 'match'),
    ('untouchable', 'Untouchable', 85, 'Dominance & Quality', true, true, 'legendary', null, 'untouchable', 'A run that didn’t flinch. The tape shows no breaks.', 'The run feels unbroken.', 'overall'),
    ('clean_sweep_week', 'Clean Sweep Week', 55, 'Dominance & Quality', true, true, 'epic', null, 'clean_sweep_week', 'Every clip in the week ended the same way.', 'A week with no counterpunches.', 'week'),
    ('high_roller', 'High Roller', 40, 'Dominance & Quality', true, true, 'rare', null, 'high_roller', 'The pace stayed high and the points kept pouring.', 'The scoreboard got a workout.', 'match'),
    ('dominant_run', 'Dominant Run', 45, 'Dominance & Quality', true, true, 'rare', null, 'dominant_run', 'The tape shows the same ending over and over.', 'The run keeps bending the same way.', 'league'),
    ('high_output', 'High Output', 40, 'Dominance & Quality', true, true, 'common', null, 'high_output', 'The scoreboard fills faster than the room expects.', 'The total keeps climbing.', 'match'),
    ('social_butterfly', 'Social Butterfly', 45, 'Versatility & Social Graph', false, true, 'rare', null, 'social_butterfly', 'The partner list turned into a montage.', 'So many different pairings on the same reel.', 'overall'),
    ('network_builder', 'Network Builder', 70, 'Versatility & Social Graph', false, true, 'epic', null, 'network_builder', 'The web stretches across the club.', 'The partner map keeps expanding.', 'overall'),
    ('draft_master', 'Draft Master', 55, 'Versatility & Social Graph', true, true, 'rare', null, 'draft_master', 'Different pairings, same result. The tape shows the range.', 'This month keeps swapping jerseys.', 'month'),
    ('swiss_army_knife', 'Swiss Army Knife', 65, 'Versatility & Social Graph', false, true, 'epic', null, 'swiss_army_knife', 'Versatility on the record. Different stages, same sharp edge.', 'The season shows more than one role.', 'season'),
    ('giant_slayer', 'Giant Slayer', 90, 'Prestige / Rarity', true, true, 'legendary', null, 'giant_slayer', 'A giant hit the floor and the camera never blinked.', 'A higher shadow fell.', 'match'),
    ('david_vs_goliath', 'David vs Goliath', 95, 'Prestige / Rarity', true, true, 'legendary', null, 'david_vs_goliath', 'The mismatch didn’t stay a mismatch.', 'The odds were heavy on one side.', 'match'),
    ('upset_champion', 'Upset Champion', 100, 'Prestige / Rarity', true, true, 'legendary', null, 'upset_champion', 'The month’s biggest swing stayed on the reel.', 'One month holds the loudest turn.', 'month'),
    ('legendary_upset', 'Legendary Upset', 120, 'Prestige / Rarity', true, true, 'legendary', null, 'legendary_upset', 'The tape caught a moment nobody predicted.', 'The odds looked impossible on this frame.', 'match'),
    ('nemesis_found', 'Nemesis Found', 55, 'Rivalry & Nemesis', false, true, 'rare', null, 'nemesis_found', 'A name keeps showing up across the net.', 'The same opponent keeps reappearing.', 'opponent'),
    ('rivalry_win', 'Rivalry Win', 60, 'Rivalry & Nemesis', true, true, 'rare', null, 'rivalry_win', 'The rivalry leaned your way on this frame.', 'One chapter shifted the rivalry.', 'match'),
    ('rivalry_streak', 'Rivalry Streak', 70, 'Rivalry & Nemesis', true, true, 'epic', null, 'rivalry_streak', 'The rivalry kept tilting, frame after frame.', 'The rivalry reel runs long.', 'opponent'),
    ('settled_the_score', 'Settled the Score', 65, 'Rivalry & Nemesis', true, true, 'epic', null, 'settled_the_score', 'The ledger finally balanced, the tape agreed.', 'A long account just evened out.', 'opponent'),
    ('battle_tested', 'Battle Tested', 50, 'Consistency & Reliability', true, true, 'rare', null, 'battle_tested', 'The season ran long and the tape kept proving it.', 'There’s weight behind this reel.', 'season'),
    ('consistency', 'Consistency', 60, 'Consistency & Reliability', true, true, 'epic', null, 'consistency', 'The tape keeps landing in the same place.', 'There’s a steady rhythm on this reel.', 'season'),
    ('steady_hand', 'Steady Hand', 55, 'Consistency & Reliability', false, true, 'rare', null, 'steady_hand', 'The season stayed smooth, even when the lights changed.', 'The season never wandered far.', 'season'),
    ('mr_reliable', 'Mr. Reliable', 80, 'Consistency & Reliability', false, false, 'epic', null, 'mr_reliable', 'Week after week, the reel looks the same.', 'Reliable tape needs reliable history.', 'season'),
    ('league_champion', 'League Champion', 140, 'Meta / Prestige', false, false, 'legendary', null, 'league_champion', 'A season ends with your name at the top.', 'The final table has a single line above the rest.', 'season'),
    ('league_runner_up', 'League Runner-Up', 120, 'Meta / Prestige', false, false, 'legendary', null, 'podium', 'Second place is still a statement.', 'Finish close enough to feel the title.', 'season'),
    ('league_third_place', 'League Third Place', 110, 'Meta / Prestige', false, false, 'legendary', null, 'podium', 'Third place keeps your season on the podium.', 'Stay in the top three when the league closes.', 'season'),
    ('top_performer_highest_rating', 'Top Performer: Highest Rating', 130, 'Top Performer Awards', true, true, 'legendary', null, 'trophy', 'The league closes with your rating on the peak.', 'Finish the season with the highest mark.', 'league'),
    ('top_performer_most_improved', 'Top Performer: Most Improved', 125, 'Top Performer Awards', true, true, 'legendary', null, 'trophy', 'The biggest climb shows up in the final tape.', 'Make the largest rating leap in the league.', 'league'),
    ('top_performer_best_win_pct', 'Top Performer: Best Win %', 120, 'Top Performer Awards', true, true, 'legendary', null, 'trophy', 'The league’s cleanest record shines at the top.', 'Finish with the best win percentage.', 'league'),
    ('top_performer_most_wins', 'Top Performer: Most Wins', 115, 'Top Performer Awards', true, true, 'legendary', null, 'trophy', 'No one stacks wins faster when the season closes.', 'Lead the league in total wins.', 'league'),
    ('podium', 'Podium', 110, 'Meta / Prestige', false, false, 'legendary', null, 'podium', 'A season ends with your name on the stage.', 'The podium holds only a few.', 'season'),
    ('hall_of_fame_night', 'Hall of Fame Night', 100, 'Meta / Prestige', true, true, 'legendary', null, 'hall_of_fame_night', 'A night that pulled the cameras in closer.', 'Some nights feel larger than the rest.', 'match'),
    ('good_sport', 'Good Sport', 35, 'Sportsmanship & Community', false, false, 'rare', null, 'good_sport', 'The tape shows respect running both ways.', 'Sportsmanship leaves quieter fingerprints.', 'overall'),
    ('community_builder', 'Community Builder', 90, 'Sportsmanship & Community', false, false, 'epic', null, 'community_builder', 'The club grew around the moments you hosted.', 'Some stories start before the match.', 'overall'),
    ('mentor', 'Mentor', 70, 'Sportsmanship & Community', false, false, 'epic', null, 'mentor', 'The tape shows the lesson without saying a word.', 'The gap was wide, the guidance wider.', 'match')

on conflict (badge_id) do update set
    name = excluded.name,
    prestige = excluded.prestige,
    category = excluded.category,
    is_stackable = excluded.is_stackable,
    is_active = excluded.is_active,
    rarity = excluded.rarity,
    tier = excluded.tier,
    icon_key = excluded.icon_key,
    lore = excluded.lore,
    hint = excluded.hint,
    scope = excluded.scope
;
