from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BadgeDefinition:
    badge_id: str
    name: str
    prestige: int
    category: str
    is_stackable: bool
    is_active: bool
    rarity: str
    tier: int | None
    icon_key: str | None
    lore: str
    hint: str
    scope: str
    state: str = "live"
    eval_triggers: tuple[str, ...] = ("match_recorded", "match_updated")


BADGE_DEFINITIONS: list[BadgeDefinition] = [
    BadgeDefinition(
        badge_id="participant",
        name="Participant",
        prestige=10,
        category="Participation & Habit Loop",
        is_stackable=False,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="participant",
        lore="Every career starts the same way: a name on the sheet and a moment on tape.",
        hint="The archive doesn’t recognize potential. Only appearances.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="dedicated_participant_50",
        name="Dedicated Participant",
        prestige=25,
        category="Participation & Habit Loop",
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="dedicated_participant_50",
        lore="Fifty matches is where routine becomes identity.",
        hint="The schedule is starting to recognize you.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="lifetime_participant_200",
        name="Lifetime Participant",
        prestige=50,
        category="Participation & Habit Loop",
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="lifetime_participant_200",
        lore="Two hundred matches doesn’t happen by accident. It happens by refusing to disappear.",
        hint="The archive is getting heavy.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="first_win",
        name="First Win",
        prestige=15,
        category="Participation & Habit Loop",
        is_stackable=False,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="first_win",
        lore="The first mark on the ledger. The tape starts rolling for real.",
        hint="There is always a first frame on the reel.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="weekly_regular",
        name="Weekly Regular",
        prestige=35,
        category="Participation & Habit Loop",
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="weekly_regular",
        lore="The schedule starts to recognize the face. The weeks keep stacking.",
        hint="The calendar keeps calling.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="iron_week",
        name="Iron Week",
        prestige=30,
        category="Participation & Habit Loop",
        is_stackable=True,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="iron_week",
        lore="A week packed tight with tape. The grind leaves a signature.",
        hint="Some weeks barely have room to breathe.",
        scope="week",
    ),
    BadgeDefinition(
        badge_id="marathon_month",
        name="Marathon Month",
        prestige=60,
        category="Participation & Habit Loop",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="marathon_month",
        lore="A month that never slowed down. Every day kept its own clip.",
        hint="The month is still writing.",
        scope="month",
    ),
    BadgeDefinition(
        badge_id="level_up",
        name="Level Up",
        prestige=40,
        category="Skill Growth & Momentum",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="level_up",
        lore="Another rung claimed. The league notices the climb.",
        hint="A new number appears on the nameplate.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="rocket_start",
        name="Rocket Start",
        prestige=50,
        category="Skill Growth & Momentum",
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="rocket_start",
        lore="The opening run shook the scoreboard. The room leaned in early.",
        hint="The first stretch left a streak on the floor.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="most_improved_monthly",
        name="Most Improved",
        prestige=55,
        category="Skill Growth & Momentum",
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="most_improved",
        lore="A month where the climb couldn’t be ignored.",
        hint="One month tilted harder than the rest.",
        scope="month",
    ),
    BadgeDefinition(
        badge_id="mountain_climber",
        name="Mountain Climber",
        prestige=45,
        category="Skill Growth & Momentum",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="mountain_climber",
        lore="Ranks flipped. The ascent left landmarks.",
        hint="The ladder looks different now.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="hot_streak",
        name="Hot Streak",
        prestige=50,
        category="Skill Growth & Momentum",
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="hot_streak",
        lore="Wins blur together on the tape. The run keeps rolling.",
        hint="The film strip barely cools off.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="bounce_back",
        name="Bounce Back",
        prestige=25,
        category="Skill Growth & Momentum",
        is_stackable=True,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="bounce_back",
        lore="A stumble, then a reply. The echo lands clean.",
        hint="The next frame told a different story.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="breakthrough",
        name="Breakthrough",
        prestige=55,
        category="Skill Growth & Momentum",
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="breakthrough",
        lore="The tape catches the moment the ceiling moves.",
        hint="There was a game when things started to look different.",
        scope="lifetime",
    ),
    BadgeDefinition(
        badge_id="above_expectations",
        name="Above Expectations",
        prestige=50,
        category="Skill Growth & Momentum",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="above_expectations",
        lore="The room expected one thing. The tape shows another.",
        hint="The projection didn’t match the result.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="ice_in_veins",
        name="Ice in Veins",
        prestige=70,
        category="Clutch & Pressure",
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="ice_in_veins",
        lore="When the margin tightened, the answer didn’t.",
        hint="Cold hands don’t shake the camera.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="clutch_performer",
        name="Clutch Performer",
        prestige=60,
        category="Clutch & Pressure",
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="clutch_performer",
        lore="Close frames keep leaning the same way.",
        hint="The last points keep finding the same jersey.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="pickle_perfection",
        name="Pickle Perfection",
        prestige=75,
        category="Dominance & Quality",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="pickle_perfection",
        lore="A shutout with no extra narration needed.",
        hint="Sometimes the other side never shows up on the scoreboard.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="blowout_artist",
        name="Blowout Artist",
        prestige=45,
        category="Dominance & Quality",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="blowout_artist",
        lore="The gap grew and never closed.",
        hint="The margin kept widening.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="untouchable",
        name="Untouchable",
        prestige=85,
        category="Dominance & Quality",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="untouchable",
        lore="A run that didn’t flinch. The tape shows no breaks.",
        hint="The run feels unbroken.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="clean_sweep_week",
        name="Clean Sweep Week",
        prestige=55,
        category="Dominance & Quality",
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="clean_sweep_week",
        lore="Every clip in the week ended the same way.",
        hint="A week with no counterpunches.",
        scope="week",
    ),
    BadgeDefinition(
        badge_id="high_roller",
        name="High Roller",
        prestige=40,
        category="Dominance & Quality",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="high_roller",
        lore="The pace stayed high and the points kept pouring.",
        hint="The scoreboard got a workout.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="dominant_run",
        name="Dominant Run",
        prestige=45,
        category="Dominance & Quality",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="dominant_run",
        lore="The tape shows the same ending over and over.",
        hint="The run keeps bending the same way.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="high_output",
        name="High Output",
        prestige=40,
        category="Dominance & Quality",
        is_stackable=True,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="high_output",
        lore="The scoreboard fills faster than the room expects.",
        hint="The total keeps climbing.",
        scope="week",
    ),
    BadgeDefinition(
        badge_id="social_butterfly",
        name="Social Butterfly",
        prestige=45,
        category="Versatility & Social Graph",
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="social_butterfly",
        lore="The partner list turned into a montage.",
        hint="So many different pairings on the same reel.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="network_builder",
        name="Network Builder",
        prestige=70,
        category="Versatility & Social Graph",
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="network_builder",
        lore="The web stretches across the club.",
        hint="The partner map keeps expanding.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="draft_master",
        name="Draft Master",
        prestige=55,
        category="Versatility & Social Graph",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="draft_master",
        lore="Different pairings, same result. The tape shows the range.",
        hint="This month keeps swapping jerseys.",
        scope="week",
    ),
    BadgeDefinition(
        badge_id="swiss_army_knife",
        name="Swiss Army Knife",
        prestige=65,
        category="Versatility & Social Graph",
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="swiss_army_knife",
        lore="Versatility on the record. Different stages, same sharp edge.",
        hint="The season shows more than one role.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="giant_slayer",
        name="Giant Slayer",
        prestige=90,
        category="Prestige / Rarity",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="giant_slayer",
        lore="A giant hit the floor and the camera never blinked.",
        hint="A higher shadow fell.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="david_vs_goliath",
        name="David vs Goliath",
        prestige=95,
        category="Prestige / Rarity",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="david_vs_goliath",
        lore="The mismatch didn’t stay a mismatch.",
        hint="The odds were heavy on one side.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="upset_champion",
        name="Upset Champion",
        prestige=100,
        category="Prestige / Rarity",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="upset_champion",
        lore="The month’s biggest swing stayed on the reel.",
        hint="One month holds the loudest turn.",
        scope="month",
    ),
    BadgeDefinition(
        badge_id="legendary_upset",
        name="Legendary Upset",
        prestige=120,
        category="Prestige / Rarity",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="legendary_upset",
        lore="The tape caught a moment nobody predicted.",
        hint="The odds looked impossible on this frame.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="nemesis_found",
        name="Nemesis Found",
        prestige=55,
        category="Rivalry & Nemesis",
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="nemesis_found",
        lore="A name keeps showing up across the net.",
        hint="The same opponent keeps reappearing.",
        scope="opponent",
    ),
    BadgeDefinition(
        badge_id="rivalry_win",
        name="Rivalry Win",
        prestige=60,
        category="Rivalry & Nemesis",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="rivalry_win",
        lore="The rivalry leaned your way on this frame.",
        hint="One chapter shifted the rivalry.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="rivalry_streak",
        name="Rivalry Streak",
        prestige=70,
        category="Rivalry & Nemesis",
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="rivalry_streak",
        lore="The rivalry kept tilting, frame after frame.",
        hint="The rivalry reel runs long.",
        scope="opponent",
    ),
    BadgeDefinition(
        badge_id="settled_the_score",
        name="Settled the Score",
        prestige=65,
        category="Rivalry & Nemesis",
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="settled_the_score",
        lore="The ledger finally balanced, the tape agreed.",
        hint="A long account just evened out.",
        scope="opponent",
    ),
    BadgeDefinition(
        badge_id="battle_tested",
        name="Battle Tested",
        prestige=50,
        category="Consistency & Reliability",
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="battle_tested",
        lore="The season ran long and the tape kept proving it.",
        hint="There’s weight behind this reel.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="consistency",
        name="Consistency",
        prestige=60,
        category="Consistency & Reliability",
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="consistency",
        lore="The tape keeps landing in the same place.",
        hint="There’s a steady rhythm on this reel.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="steady_hand",
        name="Steady Hand",
        prestige=55,
        category="Consistency & Reliability",
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="steady_hand",
        lore="The season stayed smooth, even when the lights changed.",
        hint="The season never wandered far.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="mr_reliable",
        name="Mr. Reliable",
        prestige=80,
        category="Consistency & Reliability",
        is_stackable=False,
        is_active=False,
        rarity="epic",
        tier=None,
        icon_key="mr_reliable",
        lore="Week after week, the reel looks the same.",
        hint="Reliable tape needs reliable history.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="league_champion",
        name="League Champion",
        prestige=140,
        category="Meta / Prestige",
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="league_champion",
        lore="A season ends with your name at the top.",
        hint="The final table has a single line above the rest.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="league_runner_up",
        name="League Runner-Up",
        prestige=120,
        category="Meta / Prestige",
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore="Second place is still a statement.",
        hint="Finish close enough to feel the title.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="league_third_place",
        name="League Third Place",
        prestige=110,
        category="Meta / Prestige",
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore="Third place keeps your season on the podium.",
        hint="Stay in the top three when the league closes.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="tournament_champion",
        name="Tournament Champion",
        prestige=160,
        category="Tournament Podium",
        is_stackable=False,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore="The bracket closes with your team on the top step.",
        hint="Win the tournament to claim gold.",
        scope="tournament",
    ),
    BadgeDefinition(
        badge_id="tournament_runner_up",
        name="Tournament Runner-Up",
        prestige=140,
        category="Tournament Podium",
        is_stackable=False,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore="Second place still lands on the stage.",
        hint="Finish as the tournament runner-up.",
        scope="tournament",
    ),
    BadgeDefinition(
        badge_id="tournament_third_place",
        name="Tournament Third Place",
        prestige=130,
        category="Tournament Podium",
        is_stackable=False,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore="Third place keeps your name on the podium.",
        hint="Earn the bronze finish.",
        scope="tournament",
    ),
    BadgeDefinition(
        badge_id="top_performer_highest_rating",
        name="Top Performer: Highest Rating",
        prestige=130,
        category="Top Performer Awards",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore="The league closes with your rating on the peak.",
        hint="Finish the season with the highest mark.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="top_performer_most_improved",
        name="Top Performer: Most Improved",
        prestige=125,
        category="Top Performer Awards",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore="The biggest climb shows up in the final tape.",
        hint="Make the largest rating leap in the league.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="top_performer_best_win_pct",
        name="Top Performer: Best Win %",
        prestige=120,
        category="Top Performer Awards",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore="The league’s cleanest record shines at the top.",
        hint="Finish with the best win percentage.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="top_performer_most_wins",
        name="Top Performer: Most Wins",
        prestige=115,
        category="Top Performer Awards",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore="No one stacks wins faster when the season closes.",
        hint="Lead the league in total wins.",
        scope="league",
    ),
    BadgeDefinition(
        badge_id="podium",
        name="Podium",
        prestige=110,
        category="Meta / Prestige",
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore="A season ends with your name on the stage.",
        hint="The podium holds only a few.",
        scope="season",
    ),
    BadgeDefinition(
        badge_id="hall_of_fame_night",
        name="Hall of Fame Night",
        prestige=100,
        category="Meta / Prestige",
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="hall_of_fame_night",
        lore="A night that pulled the cameras in closer.",
        hint="Some nights feel larger than the rest.",
        scope="match",
    ),
    BadgeDefinition(
        badge_id="good_sport",
        name="Good Sport",
        prestige=35,
        category="Sportsmanship & Community",
        is_stackable=False,
        is_active=False,
        rarity="rare",
        tier=None,
        icon_key="good_sport",
        lore="The tape shows respect running both ways.",
        hint="Sportsmanship leaves quieter fingerprints.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="community_builder",
        name="Community Builder",
        prestige=90,
        category="Sportsmanship & Community",
        is_stackable=False,
        is_active=False,
        rarity="epic",
        tier=None,
        icon_key="community_builder",
        lore="The club grew around the moments you hosted.",
        hint="Some stories start before the match.",
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="mentor",
        name="Mentor",
        prestige=70,
        category="Sportsmanship & Community",
        is_stackable=False,
        is_active=False,
        rarity="epic",
        tier=None,
        icon_key="mentor",
        lore="The tape shows the lesson without saying a word.",
        hint="The gap was wide, the guidance wider.",
        scope="match",
    ),
]
