from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BadgeDefinition:
    badge_id: str
    name: str
    prestige: int
    category: str
    is_stackable: bool
    is_active: bool
    rarity: str
    tier: int | None
    icon_key: str | None
    lore: str
    hint: str
    scope: str
    state: str = "live"
    eval_triggers: tuple[str, ...] = ("match_recorded", "match_updated")


BADGE_DEFINITIONS: list[BadgeDefinition] = [
    BadgeDefinition(
        badge_id="participant",
        name="Participant",
        prestige=10,
        category='Participation',
        is_stackable=False,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="participant",
        lore='Play 1 recorded match (lifetime).',
        hint='Play 1 recorded match (lifetime).',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="dedicated_participant_50",
        name="Dedicated Participant",
        prestige=25,
        category='Participation',
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="dedicated_participant_50",
        lore='Play 50 recorded matches (lifetime).',
        hint='Play 50 recorded matches (lifetime).',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="lifetime_participant_200",
        name="Lifetime Participant",
        prestige=50,
        category='Participation',
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="lifetime_participant_200",
        lore='Play 200 recorded matches (lifetime).',
        hint='Play 200 recorded matches (lifetime).',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="first_win",
        name="First Win",
        prestige=15,
        category='Participation',
        is_stackable=False,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="first_win",
        lore='Record your first win (lifetime). Any league counts.',
        hint='Record your first win (lifetime). Any league counts.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="weekly_regular",
        name="Weekly Regular",
        prestige=35,
        category='Participation',
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="weekly_regular",
        lore='In the same league, play ≥1 match in 4 consecutive ISO weeks (Mon–Sun). Missing a week breaks the streak.',
        hint='In the same league, play ≥1 match in 4 consecutive ISO weeks (Mon–Sun). Missing a week breaks the streak.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="iron_week",
        name="Iron Week",
        prestige=30,
        category='Participation',
        is_stackable=True,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="iron_week",
        lore='Play in 3+ different leagues in a single ISO week (Mon–Sun).',
        hint='Play in 3+ different leagues in a single ISO week (Mon–Sun).',
        scope="week",
    ),
    BadgeDefinition(
        badge_id="marathon_month",
        name="Marathon Month",
        prestige=60,
        category='Participation',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="marathon_month",
        lore='In the same league, play 40+ matches in a single calendar month. Earned once per league per month.',
        hint='In the same league, play 40+ matches in a single calendar month. Earned once per league per month.',
        scope="month",
    ),
    BadgeDefinition(
        badge_id="level_up",
        name="Level Up",
        prestige=40,
        category='Improvement',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="level_up",
        lore='Reach a league JUPR rating of 3.0, 3.5, 4.0, 4.5, or 5.0. Earn each milestone once; a later rating drop does not remove it.',
        hint='Reach a league JUPR rating of 3.0, 3.5, 4.0, 4.5, or 5.0. Earn each milestone once; a later rating drop does not remove it.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="rocket_start",
        name="Rocket Start",
        prestige=50,
        category='Improvement',
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="rocket_start",
        lore='In the same league, win 4+ of your first 5 matches (requires 5 recorded matches in that league).',
        hint='In the same league, win 4+ of your first 5 matches (requires 5 recorded matches in that league).',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="most_improved_monthly",
        name="Most Improved",
        prestige=55,
        category='Improvement',
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="most_improved",
        lore='Monthly (per league): Finish the month with the largest net JUPR rating gain across matches in that league. If nobody finishes net‑positive, no award.',
        hint='Monthly (per league): Finish the month with the largest net JUPR rating gain across matches in that league. If nobody finishes net‑positive, no award.',
        scope="month",
    ),
    BadgeDefinition(
        badge_id="mountain_climber",
        name="Mountain Climber",
        prestige=45,
        category='Improvement',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="mountain_climber",
        lore='In a league, improve your standing by 5 / 10 / 20 places from your starting rank. Standings are ordered by JUPR rating.',
        hint='In a league, improve your standing by 5 / 10 / 20 places from your starting rank. Standings are ordered by JUPR rating.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="hot_streak",
        name="Hot Streak",
        prestige=50,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="hot_streak",
        lore='In the same league, reach a win streak of 5 / 10 / 20 consecutive wins (milestones).',
        hint='In the same league, reach a win streak of 5 / 10 / 20 consecutive wins (milestones).',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="bounce_back",
        name="Bounce Back",
        prestige=25,
        category='Improvement',
        is_stackable=True,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="bounce_back",
        lore='Win your next recorded match after a loss (based on match history order).',
        hint='Win your next recorded match after a loss (based on match history order).',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="breakthrough",
        name="Breakthrough",
        prestige=55,
        category='Improvement',
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="breakthrough",
        lore='In a league, play 10+ matches and move from outside the top 25 / top 10 (starting rank) into the current top 25 / top 10 (by JUPR rating). Earn each tier separately.',
        hint='In a league, play 10+ matches and move from outside the top 25 / top 10 (starting rank) into the current top 25 / top 10 (by JUPR rating). Earn each tier separately.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="above_expectations",
        name="Above Expectations",
        prestige=50,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="above_expectations",
        lore='Win with expected win chance ≤ 40% and a 4+ point margin. If rating deltas are available, the match must be at or above the 75th percentile of absolute rating delta within that league.',
        hint='Win with expected win chance ≤ 40% and a 4+ point margin. If rating deltas are available, the match must be at or above the 75th percentile of absolute rating delta within that league.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="ice_in_veins",
        name="Ice in Veins",
        prestige=70,
        category='Match Achievements',
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="ice_in_veins",
        lore='Your first clutch upset: win by 2 points or fewer when your pre‑match win chance is 40% or less.',
        hint='Your first clutch upset: win by 2 points or fewer when your pre‑match win chance is 40% or less.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="clutch_performer",
        name="Clutch Performer",
        prestige=60,
        category='Match Achievements',
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="clutch_performer",
        lore='Record 5 clutch wins (wins by 2 points or fewer).',
        hint='Record 5 clutch wins (wins by 2 points or fewer).',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="pickle_perfection",
        name="Pickle Perfection",
        prestige=75,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="pickle_perfection",
        lore='Win a match without conceding a point (opponent scores 0).',
        hint='Win a match without conceding a point (opponent scores 0).',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="blowout_artist",
        name="Blowout Artist",
        prestige=45,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="blowout_artist",
        lore='Win a match by 8+ points.',
        hint='Win a match by 8+ points.',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="untouchable",
        name="Untouchable",
        prestige=85,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="untouchable",
        lore='Reach a 20+ match win streak (lifetime). Earn it again for each additional consecutive win beyond 20.',
        hint='Reach a 20+ match win streak (lifetime). Earn it again for each additional consecutive win beyond 20.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="clean_sweep_week",
        name="Clean Sweep Week",
        prestige=55,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="clean_sweep_week",
        lore='In one ISO week (Mon–Sun), play at least one match in 2+ different leagues and win them all.',
        hint='In one ISO week (Mon–Sun), play at least one match in 2+ different leagues and win them all.',
        scope="week",
    ),
    BadgeDefinition(
        badge_id="high_roller",
        name="High Roller",
        prestige=40,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="high_roller",
        lore='Record 100+ lifetime match wins.',
        hint='Record 100+ lifetime match wins.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="dominant_run",
        name="Dominant Run",
        prestige=45,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="dominant_run",
        lore='Across all leagues, reach a 10+ match win streak with average win margin ≥ 5 across the current streak. Earn it again for each additional win while the streak and average margin stay at or above the threshold.',
        hint='Across all leagues, reach a 10+ match win streak with average win margin ≥ 5 across the current streak. Earn it again for each additional win while the streak and average margin stay at or above the threshold.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="high_output",
        name="High Output",
        prestige=40,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="common",
        tier=None,
        icon_key="high_output",
        lore='Across all leagues, in your last 25 matches, record 20+ wins with average margin ≥ 4.',
        hint='Across all leagues, in your last 25 matches, record 20+ wins with average margin ≥ 4.',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="social_butterfly",
        name="Social Butterfly",
        prestige=45,
        category='Partnerships',
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="social_butterfly",
        lore='Play with 20+ different partners (lifetime). Doubles only; a recorded partner is required.',
        hint='Play with 20+ different partners (lifetime). Doubles only; a recorded partner is required.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="network_builder",
        name="Network Builder",
        prestige=70,
        category='Partnerships',
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="network_builder",
        lore='Play with 50+ different partners (lifetime). Doubles only; a recorded partner is required.',
        hint='Play with 50+ different partners (lifetime). Doubles only; a recorded partner is required.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="draft_master",
        name="Draft Master",
        prestige=55,
        category='Partnerships',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="draft_master",
        lore='In a single ISO week (Mon–Sun), record wins with 5+ different partners.',
        hint='In a single ISO week (Mon–Sun), record wins with 5+ different partners.',
        scope="week",
    ),
    BadgeDefinition(
        badge_id="swiss_army_knife",
        name="Swiss Army Knife",
        prestige=65,
        category='Participation',
        is_stackable=False,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="swiss_army_knife",
        lore='In one calendar year, record wins in 3+ different leagues.',
        hint='In one calendar year, record wins in 3+ different leagues.',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="giant_slayer",
        name="Giant Slayer",
        prestige=90,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="giant_slayer",
        lore='Win a match where the highest‑rated opponent is above 5.0.',
        hint='Win a match where the highest‑rated opponent is above 5.0.',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="david_vs_goliath",
        name="David vs Goliath",
        prestige=95,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="david_vs_goliath",
        lore='Win a match when your pre‑match win chance is 25% or less.',
        hint='Win a match when your pre‑match win chance is 25% or less.',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="upset_champion",
        name="Upset Champion",
        prestige=100,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="upset_champion",
        lore='Monthly (per league): the win with the lowest pre‑match win chance. All winners on the team receive it.',
        hint='Monthly (per league): the win with the lowest pre‑match win chance. All winners on the team receive it.',
        scope="month",
    ),
    BadgeDefinition(
        badge_id="legendary_upset",
        name="Legendary Upset",
        prestige=120,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="legendary_upset",
        lore='Win a match when your pre‑match win chance is 15% or less.',
        hint='Win a match when your pre‑match win chance is 15% or less.',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="nemesis_found",
        name="Nemesis Found",
        prestige=55,
        category='Match Achievements',
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="nemesis_found",
        lore='Against an opponent you’ve faced 6+ times, your head‑to‑head win rate is 40% or less.',
        hint='Against an opponent you’ve faced 6+ times, your head‑to‑head win rate is 40% or less.',
        scope="opponent",
    ),
    BadgeDefinition(
        badge_id="rivalry_win",
        name="Rivalry Win",
        prestige=60,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="rivalry_win",
        lore='Beat your nemesis (as defined in Nemesis Found).',
        hint='Beat your nemesis (as defined in Nemesis Found).',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="rivalry_streak",
        name="Rivalry Streak",
        prestige=70,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="rivalry_streak",
        lore='Against your nemesis, win 3 matches in a row.',
        hint='Against your nemesis, win 3 matches in a row.',
        scope="opponent",
    ),
    BadgeDefinition(
        badge_id="settled_the_score",
        name="Settled the Score",
        prestige=65,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="settled_the_score",
        lore='Against your nemesis, win a match that makes your head‑to‑head record exactly even.',
        hint='Against your nemesis, win a match that makes your head‑to‑head record exactly even.',
        scope="opponent",
    ),
    BadgeDefinition(
        badge_id="battle_tested",
        name="Battle Tested",
        prestige=50,
        category='Participation',
        is_stackable=True,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="battle_tested",
        lore='In the same season, complete 50+ matches (no forfeits / invalid matches).',
        hint='In the same season, complete 50+ matches (no forfeits / invalid matches).',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="consistency",
        name="Consistency",
        prestige=60,
        category='Participation',
        is_stackable=True,
        is_active=True,
        rarity="epic",
        tier=None,
        icon_key="consistency",
        lore='In the same season, play ≥1 match in 6 consecutive ISO weeks (missing a week breaks the streak).',
        hint='In the same season, play ≥1 match in 6 consecutive ISO weeks (missing a week breaks the streak).',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="steady_hand",
        name="Steady Hand",
        prestige=55,
        category='Match Achievements',
        is_stackable=False,
        is_active=True,
        rarity="rare",
        tier=None,
        icon_key="steady_hand",
        lore='In the same season, play 20+ matches and maintain a win rate of 60%+.',
        hint='In the same season, play 20+ matches and maintain a win rate of 60%+.',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="mr_reliable",
        name="Mr. Reliable",
        prestige=80,
        category='Match Achievements',
        is_stackable=False,
        is_active=False,
        rarity="epic",
        tier=None,
        icon_key="mr_reliable",
        lore='In the same season, play 30+ matches and finish with a 70%+ win rate.',
        hint='In the same season, play 30+ matches and finish with a 70%+ win rate.',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="league_champion",
        name="League Champion",
        prestige=140,
        category='Trophies',
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="league_champion",
        lore='Awarded on league close to the final 1st-place finisher.',
        hint='Awarded on league close to the final 1st-place finisher.',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="league_runner_up",
        name="League Runner-Up",
        prestige=120,
        category='Trophies',
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore='Awarded on league close to the final 2nd-place finisher.',
        hint='Awarded on league close to the final 2nd-place finisher.',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="league_third_place",
        name="League Third Place",
        prestige=110,
        category='Trophies',
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore='Awarded on league close to the final 3rd-place finisher.',
        hint='Awarded on league close to the final 3rd-place finisher.',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="tournament_champion",
        name="Tournament Champion",
        prestige=160,
        category='Trophies',
        is_stackable=False,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore='Finish 1st on a tournament podium.',
        hint='Finish 1st on a tournament podium.',
        scope="tournament",
    ),
    BadgeDefinition(
        badge_id="tournament_runner_up",
        name="Tournament Runner-Up",
        prestige=140,
        category='Trophies',
        is_stackable=False,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore='Finish 2nd on a tournament podium.',
        hint='Finish 2nd on a tournament podium.',
        scope="tournament",
    ),
    BadgeDefinition(
        badge_id="tournament_third_place",
        name="Tournament Third Place",
        prestige=130,
        category='Trophies',
        is_stackable=False,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore='Finish 3rd on a tournament podium.',
        hint='Finish 3rd on a tournament podium.',
        scope="tournament",
    ),
    BadgeDefinition(
        badge_id="top_performer_highest_rating",
        name="Top Performer: Highest Rating",
        prestige=130,
        category='Trophies',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore='Seasonal (league close): finish with the highest JUPR rating in the league.',
        hint='Seasonal (league close): finish with the highest JUPR rating in the league.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="top_performer_most_improved",
        name="Top Performer: Most Improved",
        prestige=125,
        category='Trophies',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore='Seasonal (league close): largest JUPR rating gain from season start to season end.',
        hint='Seasonal (league close): largest JUPR rating gain from season start to season end.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="top_performer_best_win_pct",
        name="Top Performer: Best Win %",
        prestige=120,
        category='Trophies',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore='Seasonal (league close): finish with the best win percentage in the league.',
        hint='Seasonal (league close): finish with the best win percentage in the league.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="top_performer_most_wins",
        name="Top Performer: Most Wins",
        prestige=115,
        category='Trophies',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="trophy",
        lore='Seasonal (league close): finish with the most wins in the league.',
        hint='Seasonal (league close): finish with the most wins in the league.',
        scope="league",
    ),
    BadgeDefinition(
        badge_id="podium",
        name="Podium",
        prestige=110,
        category='Trophies',
        is_stackable=False,
        is_active=False,
        rarity="legendary",
        tier=None,
        icon_key="podium",
        lore='Awarded on league close to any top-3 finisher.',
        hint='Awarded on league close to any top-3 finisher.',
        scope="season",
    ),
    BadgeDefinition(
        badge_id="hall_of_fame_night",
        name="Hall of Fame Night",
        prestige=100,
        category='Match Achievements',
        is_stackable=True,
        is_active=True,
        rarity="legendary",
        tier=None,
        icon_key="hall_of_fame_night",
        lore='In a league, win a match with a top‑5% rating swing for that league (by absolute JUPR rating change).',
        hint='In a league, win a match with a top‑5% rating swing for that league (by absolute JUPR rating change).',
        scope="match",
    ),
    BadgeDefinition(
        badge_id="good_sport",
        name="Good Sport",
        prestige=35,
        category='Partnerships',
        is_stackable=False,
        is_active=False,
        rarity="rare",
        tier=None,
        icon_key="good_sport",
        lore='Awarded manually for outstanding sportsmanship.',
        hint='Awarded manually for outstanding sportsmanship.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="community_builder",
        name="Community Builder",
        prestige=90,
        category='Partnerships',
        is_stackable=False,
        is_active=False,
        rarity="epic",
        tier=None,
        icon_key="community_builder",
        lore='Awarded manually for meaningful community impact.',
        hint='Awarded manually for meaningful community impact.',
        scope="overall",
    ),
    BadgeDefinition(
        badge_id="mentor",
        name="Mentor",
        prestige=70,
        category='Partnerships',
        is_stackable=False,
        is_active=False,
        rarity="epic",
        tier=None,
        icon_key="mentor",
        lore='Awarded manually for mentorship contributions.',
        hint='Awarded manually for mentorship contributions.',
        scope="match",
    ),
]
