import { expect, test } from "@playwright/test";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import type { MeetSignupBoard, PrivateMeetSignup } from "../lib/interclubMeetSignup";
import type { PoolMember } from "../lib/interclubPlayerPool";
import type { PublicLeague } from "../lib/interclubPublic";
import { bootstrapStagingContext, expectedApiOrigin } from "./support/staging";

function expectLinkedPoolMember(members: PoolMember[], name: string, rating: number, gender: string) {
  const matching = members.filter(member => member.name === name);
  expect(matching.length, "Inline creation must save exactly one linked season signup").toBe(1);
  const member = matching[0];
  expect(Number(member.player_id)).toBeGreaterThan(0);
  expect(member.rating).toBe(rating);
  expect(member.gender).toBe(gender);
  expect(member.eligible_divisions).toContain("3.5");
  expect(member.status).toBe("active");
  return member;
}

// This private fixture stays outside uploaded artifacts. The session was issued
// by staging Auth to a synthetic user restricted to this run's synthetic clubs.
test.use({ trace: "off", video: "off", screenshot: "off", timezoneId: "UTC" });
test("interclub paper packet, score entry, approval and public results", async ({ page, context, browser }) => {
  test.setTimeout(300_000);
  const state = JSON.parse(readFileSync(process.env.JUPR_INTERCLUB_REHEARSAL_STATE!, "utf8"));
  expect(state.marker).toBe("interclub-functional-rehearsal-v1");
  expect(state.sha).toBe(process.env.GITHUB_SHA);
  const origin = process.env.JUPR_ATTESTED_VERCEL_DEPLOYMENT_ORIGIN!;
  const user = state.users[0];
  const club = state.clubs[0];
  const season = state.seasons.find((s: { label: string }) => s.label === "incidents");
  const official = state.seasons.find((s: { label: string }) => s.label === "full-season");
  const signup = state.seasons.find((s: { label: string }) => s.label === "browser-signup");
  expect(season.registration.status).toBe("closed");
  expect(official.registration.status).toBe("closed");
  expect(signup.registration.status).toBe("open");
  const reportDir = process.env.JUPR_INTERCLUB_REHEARSAL_REPORT!;
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await bootstrapStagingContext(context);
  await context.addInitScript(({ token: access_token, email, origin }) => {
    if (location.origin === origin) localStorage.setItem("jupr_admin_session_v1", JSON.stringify({
      access_token, token_type: "bearer", user: { email },
    }));
  }, { token: user.token, email: user.email, origin });
  await context.addCookies([{ name: "jupr_admin_workspace_v1", value: encodeURIComponent(JSON.stringify({ clubId: club, clubSlug: club })),
    url: origin, secure: true, sameSite: "Lax" }]);
  const route = `/admin/interclub/competition?season=${season.id}&meet=${season.browser_meet}`;
  const apiRoot = `${expectedApiOrigin}/admin/clubs/${club}/interclub/competition/${season.id}/meets/${season.browser_meet}/regular`;
  const initialMeet = page.waitForResponse(r => r.url() === apiRoot && r.request().method() === "GET");
  await page.goto(route);
  const scheduledMeetDate = (await (await initialMeet).json()).meet.starts_at;
  expect(Date.parse(scheduledMeetDate)).toBeGreaterThan(Date.now());
  await expect(page.getByRole("combobox", { name: "Court schedule", exact: true })).toHaveValue("staggered", { timeout: 30_000 });
  const generation = page.waitForResponse(r => r.url() === apiRoot+"/generate" && r.request().method() === "POST");
  await page.getByRole("button", { name: "Generate pairings", exact: true }).click();
  const generated = await generation;
  expect(generated.status()).toBe(200);
  season.browser_batch = (await generated.json()).batch;
  expect(season.browser_batch.document.schedule_mode).toBe("staggered");
  await expect(page.getByRole("heading", { name: "Meet score draft", exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByRole("region", { name: "Court schedule", exact: true }).getByRole("columnheader", { name: "Wave", exact: true })).toBeVisible();
  const courtSchedule = page.getByRole("region", { name: "Court schedule", exact: true });
  await expect(courtSchedule.getByText(/finish all three games, even at 2-0, before leaving/)).toBeVisible();
  await expect(courtSchedule.getByRole("cell", { name: "1-3", exact: true })).toHaveCount(
    season.browser_batch.document.encounters.reduce((total: number, encounter: { pairings: unknown[] }) => total + encounter.pairings.length, 0));
  await page.screenshot({ path: join(reportDir, "interclub-staggered-schedule.png"), fullPage: true });
  await page.getByRole("button", { name: "Review and submit meet", exact: true }).click();
  await expect(page.getByRole("button", { name: "Submit all official scores", exact: true })).toBeDisabled();
  await expect(page.getByRole("link", { name: "Go to the first incomplete game", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Keep reviewing", exact: true }).click();
  await expect(page.getByRole("button", { name: "Print meet packet", exact: true })).toBeEnabled();
  for (const scope of ["schedule", "full packet"]) {
    const downloaded = page.waitForEvent("download");
    await page.getByRole("button", { name: `Download ${scope} PDF`, exact: true }).click();
    const download = await downloaded;
    expect(download.suggestedFilename()).toMatch(/-(schedule|packet)-r1\.pdf$/);
    const file = join(reportDir, `interclub-download-${scope.replace(" ", "-")}.pdf`);
    await download.saveAs(file);
    expect(readFileSync(file).subarray(0,5).toString()).toBe("%PDF-");
  }
  await page.emulateMedia({ media: "print" });
  await page.pdf({ path: join(reportDir, "interclub-paper-packet.pdf"), format: "A4", printBackground: true });
  await page.emulateMedia({ media: "screen" });
  const scoreInputs = page.locator("input[data-interclub-score]");
  const scoreCount = await scoreInputs.count();
  expect(scoreCount).toBe(12);
  await expect(page.getByLabel("Actual time played (your device’s time)", { exact: true })).toHaveCount(0);
  const entryStartedAt = await page.evaluate(() => Date.now());
  await scoreInputs.first().click();
  await page.keyboard.type("5");
  await page.keyboard.press("Tab");
  await expect(scoreInputs.nth(1)).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  await expect(scoreInputs.first()).toBeFocused();
  for (let index = 0; index < scoreCount; index++) {
    await expect(scoreInputs.nth(index)).toBeFocused();
    await page.keyboard.type(index % 2 ? "9" : "11");
    await expect(scoreInputs.nth(index)).toHaveValue(index % 2 ? "9" : "11");
    await page.keyboard.press("Tab");
  }
  await expect(page.getByRole("button", { name: "Save all draft scores", exact: true }).last()).toBeFocused();
  await expect(page.locator("[data-score-game]").getByText("Completed", { exact: true })).toHaveCount(scoreCount / 2);
  await expect(page.getByRole("combobox", { name: /^Season/ })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Print meet packet", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Download schedule PDF", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Download full packet PDF", exact: true })).toBeDisabled();
  const save = page.waitForResponse(r => r.url() === apiRoot && r.request().method() === "PUT");
  await page.keyboard.press("Enter");
  const savedScores = await save;
  expect(savedScores.status()).toBe(200);
  const savedScoreBatch = (await savedScores.json()).batch;
  for (const encounter of savedScoreBatch.document.encounters) for (const pairing of encounter.pairings) for (const game of pairing.games) {
    expect(Date.parse(game.played_at)).toBeGreaterThanOrEqual(entryStartedAt);
    expect(Date.parse(game.played_at)).toBeLessThanOrEqual(await page.evaluate(() => Date.now()));
    expect(Date.parse(game.played_at)).toBeLessThan(Date.parse(scheduledMeetDate));
  }
  await expect(page.getByText("All draft changes saved", { exact: true })).toBeVisible();
  // Exercise both a new one-time injury entry and a draft left by the old
  // per-game editor. All writes are confined to this run's synthetic meet.
  const meetRead = await context.request.get(apiRoot, { headers: { Authorization: `Bearer ${user.token}` } });
  expect(meetRead.status()).toBe(200);
  const meetDetail = await meetRead.json();
  const injuredEncounter = savedScoreBatch.document.encounters[0];
  const injuredPair = injuredEncounter.pairings.find((p: { kind: string }) => p.kind === "women");
  const injuredGame = injuredPair.games[1];
  const substitute = meetDetail.eligible_players[injuredEncounter.club_a].find((p: { entry_id: string; gender: string; eligibility_rating?: number; rating?: number; starting_rating?: number }) =>
    Number(p.eligibility_rating ?? p.rating ?? p.starting_rating) < Number(injuredEncounter.division) + .5 && ["female", "f"].includes(p.gender.toLowerCase()) && !injuredPair.players_a.includes(p.entry_id));
  expect(substitute, "Synthetic meet has an eligible female reserve").toBeTruthy();
  const gameCard = page.locator(`[id="interclub-game-${injuredGame.id}"]`);
  await gameCard.getByText("Substitute a player · Game 2", { exact: true }).click();
  await expect(gameCard.getByRole("combobox", { name: "Injured player", exact: true })).toBeVisible();
  await gameCard.getByLabel("Injured player", { exact: true }).selectOption(`a:${injuredPair.players_a[0]}`);
  await gameCard.getByRole("combobox", { name: "Replacement", exact: true }).fill(substitute.name);
  await gameCard.getByRole("option", { name: substitute.name, exact: true }).click();
  await gameCard.getByRole("button", { name: "Apply substitution to remaining games", exact: true }).click();
  const substitutionSave = page.waitForResponse(r => r.url() === apiRoot && r.request().method() === "PUT");
  await page.getByRole("button", { name: "Save all draft scores", exact: true }).last().click();
  const substitutionResponse = await substitutionSave;
  expect(substitutionResponse.status()).toBe(200);
  const appliedBatch = (await substitutionResponse.json()).batch;
  await expect(page.getByRole("button", { name: "Undo substitution update", exact: true })).toHaveCount(0);
  const appliedPair = appliedBatch.document.encounters[0].pairings.find((p: { id: string }) => p.id === injuredPair.id);
  expect(appliedPair.games[0]).toEqual(injuredPair.games[0]);
  for (const other of injuredEncounter.pairings.filter((p: { id: string }) => p.id !== injuredPair.id)) {
    expect(appliedBatch.document.encounters[0].pairings.find((p: { id: string }) => p.id === other.id)).toEqual(other);
  }
  for (const game of appliedPair.games.slice(1)) {
    expect(game.players_a).toContain(substitute.entry_id);
    expect(game.players_a).not.toContain(injuredPair.players_a[0]);
    expect(game.injury_reason).toBe("Injury");
  }
  const legacyDraft = JSON.parse(JSON.stringify(savedScoreBatch.document));
  const legacyGame = legacyDraft.encounters[0].pairings.find((p: { id: string }) => p.id === injuredPair.id).games[1];
  legacyGame.players_a = [substitute.entry_id, injuredPair.players_a[1]];
  legacyGame.injury_reason = null;
  const legacySave = await context.request.put(apiRoot, { headers: { Authorization: `Bearer ${user.token}` }, data: { expected_revision: appliedBatch.revision, document: legacyDraft } });
  expect(legacySave.status()).toBe(200);
  await page.reload();
  const attention = page.getByRole("region", { name: "Substitutions needing attention", exact: true });
  await expect(attention.getByRole("heading", { name: "One substitution needs attention", exact: true })).toBeVisible();
  await attention.getByRole("button", { name: "Show this substitution", exact: true }).click();
  await expect(gameCard).toBeFocused();
  await expect(gameCard.locator("details[data-substitution]")).toHaveAttribute("open", "");
  await attention.getByRole("button", { name: "Carry substitute forward", exact: true }).click();
  await expect(attention).toHaveCount(0);
  const repairedSave = page.waitForResponse(r => r.url() === apiRoot && r.request().method() === "PUT");
  await page.getByRole("button", { name: "Save all draft scores", exact: true }).last().click();
  expect((await repairedSave).status()).toBe(200);
  await page.reload();
  await expect(page.getByRole("button", { name: "Review and submit meet", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Review and submit meet", exact: true }).click();
  await page.getByRole("button", { name: "Submit all official scores", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Awaiting organizer approval", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Review official approval", exact: true }).click();
  const approval = page.waitForResponse(r => r.url() === apiRoot+"/approve" && r.request().method() === "POST", { timeout: 90_000 });
  await page.getByRole("button", { name: "Approve this revision", exact: true }).click();
  const result = await approval;
  expect(result.status()).toBe(200);
  expect((await result.json()).ratings.status).toBe("completed");
  await expect(page.getByRole("heading", { name: "Official meet results", exact: true })).toBeVisible();
  await expect(page.getByText("Rating updates: completed", { exact: true })).toBeVisible();
  await expect(page.locator("input[data-interclub-score]")).toHaveCount(0);
  const reviewedResults = page.getByRole("region", { name: "Browse match results", exact: true });
  await expect(reviewedResults).toBeVisible();
  await expect(reviewedResults.getByRole("combobox", { name: "Filter results by club", exact: true })).toBeVisible();
  await expect(reviewedResults.getByRole("table", { name: "Game results", exact: true })).toBeVisible();
  await expect(reviewedResults.locator("tr[data-result-game]")).toHaveCount(scoreCount / 2);
  await expect(reviewedResults.locator("details")).toHaveCount(0);
  await page.screenshot({ path: join(reportDir,"interclub-approved-meet.png"), fullPage: true });

  const championshipContext = page.waitForResponse(r => new URL(r.url()).pathname === `/admin/clubs/${club}/interclub/competition/${official.id}` && r.request().method() === "GET");
  await page.goto(`/admin/interclub/competition?season=${official.id}`);
  const completedSeason = await (await championshipContext).json();
  await expect(page.getByRole("heading", { name: "Championships", exact: true })).toBeVisible();
  const championshipPanel = page.getByRole("region", { name: "Championship results", exact: true });
  await expect(championshipPanel).toBeVisible();
  await expect(page.getByRole("combobox", { name: "Meet", exact: true })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Meet score draft", exact: true })).toHaveCount(0);
  for (const division of completedSeason.season.details.divisions) {
    const qualified = championshipPanel.getByRole("article", { name: `${division} championship qualification`, exact: true });
    await expect(qualified).toBeVisible();
    for (const id of completedSeason.standings.qualification[division].qualifiers) {
      await expect(qualified.getByRole("heading")).toContainText(completedSeason.clubs.find((candidate: { id: string }) => candidate.id === id).name);
    }
    await expect(qualified.getByText("Final results approved", { exact: true })).toBeVisible();
  }
  await page.screenshot({ path: join(reportDir, "interclub-championship-panel.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: join(reportDir, "interclub-championship-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole("button", { name: "Regular-season results", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Official meet results", exact: true })).toBeVisible();
  await page.locator("summary").filter({ hasText: /^Add meet$/ }).click();
  await page.getByLabel("Competition", { exact: true }).selectOption("final");
  const qualifiedSetup = page.getByRole("region", { name: "Qualified clubs", exact: true });
  await expect(qualifiedSetup.getByRole("heading", { name: "Finalists from season results", exact: true })).toBeVisible();
  await expect(page.getByLabel("Duration (minutes)", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("checkbox")).toHaveCount(0);
  const qualifiedClubIds = [...new Set(Object.values(completedSeason.standings.qualification).flatMap((q: any) => q.qualifiers))].sort();
  expect(await page.getByLabel("Host club", { exact: true }).locator("option").evaluateAll(options => options.map(option => (option as HTMLOptionElement).value).filter(Boolean).sort())).toEqual(qualifiedClubIds);
  await page.screenshot({ path: join(reportDir, "interclub-final-setup.png"), fullPage: true });

  const finalRoot = `${expectedApiOrigin}/admin/clubs/${club}/interclub/competition/${official.id}/meets/${official.browser_final}/final`;
  const finalRead = page.waitForResponse(r => r.url() === finalRoot && r.request().method() === "GET");
  await page.goto(`/admin/interclub/competition?season=${official.id}&meet=${official.browser_final}`);
  const finalDetail = await (await finalRead).json();
  const sweep = finalDetail.batch.document.encounters[0];
  expect(sweep.pairings[3].games[0].status).toBe("not_needed");
  await page.locator("summary").filter({ hasText: /^Correct submitted or official scores$/ }).click();
  await page.getByLabel("Reason for correction", { exact: true }).fill("Verify 3-0 championship score entry and correction");
  await page.getByRole("button", { name: "Open correction draft", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Meet score draft", exact: true })).toBeVisible();
  await expect(page.locator("[data-not-needed-game]")).toHaveCount(1);
  const finalScore = (pair: number, side: string) => page.getByRole("spinbutton", { name: `${sweep.pairings[pair].id} game 1 club ${side} score`, exact: true });
  await finalScore(0, "B").fill("13");
  await expect(page.locator("[data-not-needed-game]")).toHaveCount(0);
  await expect(finalScore(3, "A")).toBeVisible();
  for (const pair of [0, 1, 2]) for (const side of ["A", "B"]) await finalScore(pair, side).clear();
  await finalScore(0, "A").click();
  for (const pair of [0, 1, 2]) {
    await expect(finalScore(pair, "A")).toBeFocused();
    await page.keyboard.type("11"); await page.keyboard.press("Tab");
    await expect(finalScore(pair, "B")).toBeFocused();
    await page.keyboard.type("5"); await page.keyboard.press("Tab");
  }
  await expect(page.locator("[data-not-needed-game]")).toHaveCount(1);
  await expect(finalScore(3, "A")).toHaveCount(0);
  const nextFinal = finalDetail.batch.document.encounters[1];
  await expect(page.getByRole("spinbutton", { name: `${nextFinal.pairings[0].id} game 1 club A score`, exact: true })).toBeFocused();
  await page.screenshot({ path: join(reportDir, "interclub-championship-clinch.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: join(reportDir, "interclub-championship-clinch-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  const finalSave = page.waitForResponse(r => r.url() === finalRoot && r.request().method() === "PUT");
  await page.getByRole("button", { name: "Save all draft scores", exact: true }).last().click();
  const savedFinal = await finalSave;
  expect(savedFinal.status()).toBe(200);
  const finalBatch = (await savedFinal.json()).batch;
  expect(finalBatch.document.encounters[0].pairings[3].games[0].status).toBe("not_needed");
  expect(finalBatch.document.encounters[0].tiebreak).toBeNull();
  expect(finalBatch.document.encounters[1].tiebreak.status).toBe("completed");
  await page.reload();
  await expect(page.locator("[data-not-needed-game]")).toHaveCount(1);
  await expect(page.getByText("11 of 11 game outcomes entered · Saved", { exact: true })).toBeVisible();
  const finalPdf = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download full packet PDF", exact: true }).click();
  await (await finalPdf).saveAs(join(reportDir, "interclub-championship-clinch.pdf"));
  await page.getByRole("button", { name: "Review and submit meet", exact: true }).click();
  await expect(page.getByRole("button", { name: "Submit all official scores", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Submit all official scores", exact: true }).click();
  await page.getByRole("button", { name: "Review official approval", exact: true }).click();
  const finalApproval = page.waitForResponse(r => r.url() === finalRoot+"/approve" && r.request().method() === "POST", { timeout: 90_000 });
  await page.getByRole("button", { name: "Approve this revision", exact: true }).click();
  const approvedFinal = await finalApproval;
  expect(approvedFinal.status()).toBe(200);
  expect((await approvedFinal.json()).ratings.status).toBe("completed");
  await expect(page.getByRole("heading", { name: "Official meet results", exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Browse match results", exact: true }).getByText("Not needed — matchup decided 3–0", { exact: true })).toBeVisible();

  const awardsRoot = `${expectedApiOrigin}/admin/clubs/${club}/interclub/${official.id}/awards`;
  const awardPreview = page.waitForResponse(r => r.url() === awardsRoot && r.request().method() === "GET");
  await page.goto(`/admin/interclub/awards?season=${official.id}`);
  const previewResponse = await awardPreview;
  expect(previewResponse.status()).toBe(200);
  const reviewedAwards = await previewResponse.json();
  expect(reviewedAwards.ready).toBe(true);
  expect(reviewedAwards.current).toBe(false);
  await expect(page.getByRole("heading", { name: "Season awards", exact: true })).toBeVisible();
  const awardButton = page.getByRole("button", { name: "Publish final results and update trophies", exact: true });
  await expect(awardButton).toBeDisabled();
  await page.getByRole("checkbox", { name: "I have reviewed the final results and trophy recipients.", exact: true }).check();
  const awarded = page.waitForResponse(r => r.url() === awardsRoot && r.request().method() === "POST");
  await awardButton.click();
  expect((await awarded).status()).toBe(200);
  await expect(page.getByText("Season trophies awarded. These honors match the current final results.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: /Publish final results/ })).toHaveCount(0);
  await page.reload();
  await expect(page.getByText("Season trophies awarded. These honors match the current final results.", { exact: true })).toBeVisible();
  await page.screenshot({ path: join(reportDir, "interclub-season-awards-admin.png"), fullPage: true });

  const lockedReads: string[] = [];
  page.on("request", request => {
    const path = new URL(request.url()).pathname;
    if (request.method() === "GET" && ["registrations", "competition"].some(area => path.startsWith(`/admin/clubs/${club}/interclub/${area}/${signup.id}/meets/`))) lockedReads.push(path);
  });
  const signupContext = page.waitForResponse(r => new URL(r.url()).pathname === `/admin/clubs/${club}/interclub/competition/${signup.id}` && r.request().method() === "GET");
  await page.goto(`/admin/interclub/competition?season=${signup.id}&meet=${signup.meets[0].id}`);
  const signupResponse = await signupContext;
  expect(signupResponse.status()).toBe(200);
  expect((await signupResponse.json()).season.id).toBe(signup.id);
  await expect(page.getByRole("heading", { name: "Meet planning opens after registration closes", exact: true })).toBeVisible();
  await expect(page.locator("summary").filter({ hasText: /^Season standings & Club Cup$/ })).toHaveCount(0);
  await expect(page.getByRole("combobox", { name: "Meet", exact: true, includeHidden: true })).toHaveCount(0);
  await page.getByRole("link", { name: "Go to season player pool", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Season registration", exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Season player pool", exact: true })).toBeVisible();
  const workflow = page.getByRole("navigation", { name: "League workflow", exact: true });
  await expect(workflow.getByRole("link", { name: "Player pool", exact: true })).toHaveAttribute("aria-current", "step");
  for (const label of ["Meet signup", "Lineups", "Run meet", "Approve results"]) {
    await expect(workflow.getByRole("link", { name: label, exact: true })).toHaveCount(0);
    await expect(workflow.locator('[aria-disabled="true"]').filter({ has: page.getByText(label, { exact: true }) })).toHaveCount(1);
  }
  await expect(page.getByRole("combobox", { name: "Meet", exact: true, includeHidden: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Reload meet", exact: true, includeHidden: true })).toHaveCount(0);
  expect(lockedReads, "An open signup season must not fetch operational meet details even from a direct URL").toEqual([]);

  const signupPoolRoot = `${expectedApiOrigin}/admin/clubs/${club}/interclub/registrations/${signup.id}/pool`;
  const adminPlayerName = `Browser admin new ${state.run}`;
  const signupPool = page.getByRole("region", { name: "Season player pool", exact: true });
  await signupPool.getByRole("button", { name: "Create new player", exact: true }).click();
  const newPlayer = signupPool.getByRole("region", { name: "Create a new club player", exact: true });
  await newPlayer.getByLabel("Player name", { exact: true }).fill(adminPlayerName);
  await newPlayer.getByRole("spinbutton", { name: /^Starting JUPR/ }).fill("3.25");
  await newPlayer.getByLabel("Gender (optional)", { exact: true }).selectOption("female");
  await expect(newPlayer.getByLabel("Email (optional)", { exact: true })).toHaveValue("");
  const adminCreated = page.waitForResponse(r => r.url() === `${signupPoolRoot}/create-player` && r.request().method() === "POST");
  await newPlayer.getByRole("button", { name: "Create player and add to pool", exact: true }).click();
  const adminCreatedResponse = await adminCreated;
  expect(adminCreatedResponse.status()).toBe(200);
  const adminCreatedResult = await adminCreatedResponse.json();
  const adminMember = expectLinkedPoolMember(adminCreatedResult.pool.members, adminPlayerName, 3.25, "female");
  expect(adminCreatedResult.member.id).toBe(adminMember.id);
  expect(String(adminCreatedResult.member.player_id)).toBe(String(adminMember.player_id));
  expect(adminMember.email).toBe("");
  const adminPlayerRow = signupPool.getByRole("row").filter({ has: page.getByRole("rowheader").filter({ hasText: adminPlayerName }) });
  await expect(adminPlayerRow).toHaveCount(1);
  await expect(adminPlayerRow.getByRole("cell", { name: "3.25", exact: true }).first()).toBeVisible();
  await expect(adminPlayerRow.getByRole("cell", { name: "Women", exact: true })).toBeVisible();

  const adjustments = state.seasons.find((s: { label: string }) => s.label === "season-adjustments");
  await page.goto(`/admin/interclub/registrations?season=${adjustments.id}`);
  const schedule = page.getByRole("region", { name: "Meet schedule", exact: true });
  await expect(schedule.getByRole("button", { name: "Add meet", exact: true })).toBeEnabled();
  await expect(schedule.getByRole("row")).toHaveCount(3);
  await schedule.getByRole("button", { name: /^Edit date for/ }).first().click();
  await expect(schedule.getByLabel("Duration (minutes)", { exact: true })).toHaveCount(0);
  const localDate = (date: Date) => new Intl.DateTimeFormat("sv-SE", { timeZone: "America/Mazatlan", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" })
    .format(date).replace(" ", "T");
  await schedule.getByLabel("Meet date and time", { exact: true }).fill(localDate(new Date(Date.parse(adjustments.meets[0].starts_at)+86_400_000)));
  const rescheduled = page.waitForResponse(r => r.url().endsWith(`/meets/${adjustments.meets[0].id}/schedule`) && r.request().method() === "PUT");
  await schedule.getByRole("button", { name: "Save meet date", exact: true }).click();
  expect((await rescheduled).status()).toBe(200);
  await expect(schedule.getByRole("status").filter({ hasText: "Meet schedule saved." })).toBeVisible();
  await schedule.getByRole("button", { name: "Add meet", exact: true }).click();
  await expect(schedule.getByLabel("Competition", { exact: true })).toHaveValue("regular");
  await expect(schedule.getByLabel("Duration (minutes)", { exact: true })).toHaveCount(0);
  await expect(schedule.getByText(/Season dates:/)).toBeVisible();
  await schedule.getByLabel("Host club", { exact: true }).selectOption(club);
  for (const checkbox of await schedule.getByRole("checkbox").all()) {
    if (!(await checkbox.isChecked())) await checkbox.check();
  }
  await schedule.getByLabel("Meet date and time", { exact: true }).fill(localDate(new Date(Date.now()+11*86_400_000)));
  await schedule.getByLabel("Roster deadline", { exact: true }).fill(localDate(new Date(Date.now()+10*86_400_000)));
  const added = page.waitForResponse(r => r.url().endsWith(`/competition/${adjustments.id}/meets`) && r.request().method() === "POST");
  await schedule.getByRole("button", { name: "Add meet", exact: true }).click();
  const addedResponse = await added;
  expect(addedResponse.status()).toBe(200);
  const addedMeet = (await addedResponse.json()).meet;
  await expect(schedule.getByRole("row")).toHaveCount(4);
  const pool = page.getByRole("region", { name: "Season player pool", exact: true });
  await pool.getByRole("button", { name: "Request late player", exact: true }).click();
  const lateRequest = pool.getByRole("region", { name: "Request a late player", exact: true });
  await lateRequest.getByRole("button", { name: "Create new player", exact: true }).click();
  await lateRequest.getByLabel("Player name", { exact: true }).fill(adjustments.browser_late_player);
  await lateRequest.getByRole("spinbutton", { name: /^Starting JUPR/ }).fill("3.35");
  await lateRequest.getByLabel("Gender (optional)", { exact: true }).selectOption("male");
  await expect(lateRequest.getByLabel("Notes (optional)", { exact: true })).toHaveValue("");
  const lateCreated = page.waitForResponse(r => r.url() === `${expectedApiOrigin}/admin/clubs/${club}/interclub/registrations/${adjustments.id}/pool/late-requests` && r.request().method() === "POST");
  await lateRequest.getByRole("button", { name: "Create player and request late entry", exact: true }).click();
  const lateCreatedResponse = await lateCreated;
  expect(lateCreatedResponse.status()).toBe(200);
  const lateCreatedResult = await lateCreatedResponse.json();
  const lateMember = expectLinkedPoolMember(lateCreatedResult.pool.members, adjustments.browser_late_player, 3.35, "male");
  expect(lateCreatedResult.member.id).toBe(lateMember.id);
  expect(String(lateCreatedResult.member.player_id)).toBe(String(lateMember.player_id));
  expect(lateMember.approval_status).toBe("pending");
  expect(lateMember.late_join).toBe(true);
  expect(lateMember.late_request_reason || "").toBe("");
  const latePlayerRow = pool.getByRole("row").filter({ has: page.getByRole("rowheader").filter({ hasText: adjustments.browser_late_player }) });
  await expect(latePlayerRow.getByRole("cell", { name: "Pending · cannot play", exact: true })).toBeVisible();
  const approvals = page.getByRole("region", { name: "Season eligibility approvals", exact: true });
  const applicant = approvals.getByRole("article").filter({ has: page.getByRole("heading", { name: adjustments.browser_late_player, exact: true }) });
  await expect(applicant.getByText(/Pending approval/)).toBeVisible();
  await applicant.getByLabel("Decision reason", { exact: true }).fill("Commissioner approves the late commitment.");
  const lateApproved = page.waitForResponse(r => r.url() === `${expectedApiOrigin}/admin/clubs/${club}/interclub/registrations/${adjustments.id}/pool/approvals` && r.request().method() === "POST");
  await applicant.getByRole("button", { name: "Approve season eligibility", exact: true }).click();
  const lateApprovedResponse = await lateApproved;
  expect(lateApprovedResponse.status()).toBe(200);
  const approvedMember = (await lateApprovedResponse.json()).member;
  expect(approvedMember.id).toBe(lateMember.id);
  expect(approvedMember.approval_status).toBe("approved");
  await expect(approvals.getByRole("status").filter({ hasText: `${adjustments.browser_late_player}: approved for the season pool.` })).toBeVisible();
  await page.screenshot({ path: join(reportDir, "interclub-season-adjustments.png"), fullPage: true });

  // Follow the same path an administrator uses after adding a meet. No
  // availability invitation is needed for verbally confirmed players.
  await schedule.getByRole("link", { name: "Choose players for this meet", exact: true }).click();
  await expect(page.getByRole("navigation", { name: "League workflow" }).getByRole("link", { name: "Lineups", exact: true })).toHaveAttribute("aria-current", "step");
  await expect(page.getByLabel("Meet", { exact: true })).toHaveValue(addedMeet.id);
  const playerResponse = page.waitForResponse(r => r.url().includes(`/registrations/${adjustments.id}/meets/`) && new URL(r.url()).pathname.endsWith("/players"));
  await page.getByRole("button", { name: "Add a team for this meet", exact: true }).click();
  const availablePlayers = (await (await playerResponse).json()).players as { id: string; name: string; eligibility_rating: number; gender: string }[];
  const roster = page.getByRole("form", { name: "Choose meet players", exact: true });
  await roster.getByLabel("Lineup division", { exact: true }).selectOption("3.5");
  await expect(roster.getByLabel("Player eligibility filter", { exact: true })).toHaveValue("eligible");
  const selectedPlayers = ["female", "male"].flatMap(gender => availablePlayers.filter(player => player.gender === gender && player.eligibility_rating > 0 && player.eligibility_rating < 4).slice(0, 2));
  expect(selectedPlayers).toHaveLength(4);
  for (const player of selectedPlayers) await roster.getByRole("checkbox", { name: `Select ${player.name}`, exact: true }).check();
  await expect(roster.getByRole("status", { name: "Lineup selection" })).toContainText("2 of 2 women · 2 of 2 men");
  await page.screenshot({ path: join(reportDir, "interclub-guided-player-picker.png"), fullPage: true });
  await roster.getByRole("button", { name: "Review season player pool", exact: true }).click();
  await expect(pool).toBeVisible();
  await page.getByRole("navigation", { name: "League workflow" }).getByRole("link", { name: "Lineups", exact: true }).click();
  for (const player of selectedPlayers) await expect(roster.getByRole("checkbox", { name: `Select ${player.name}`, exact: true })).toBeChecked();
  const rosterSaved = page.waitForResponse(r => r.url().includes(`/registrations/${adjustments.id}/meets/`) && r.url().includes("/teams/") && r.request().method() === "PUT");
  await roster.getByRole("button", { name: "Submit four-player roster", exact: true }).click();
  const rosterResult = await rosterSaved;
  expect(rosterResult.status()).toBe(200);
  const savedTeam = (await rosterResult.json()).team;
  expect(savedTeam.status).toBe("eligible");
  expect(savedTeam.roster.map((player: { player_id: string }) => String(player.player_id)).sort()).toEqual(selectedPlayers.map(player => String(player.id)).sort());
  await expect(page.getByRole("status").filter({ hasText: "Lineup saved for this meet." })).toBeVisible();
  await page.screenshot({ path: join(reportDir, "interclub-guided-lineup.png"), fullPage: true });

  // Account-free signup and concurrent allocation into the actual lineup.
  const queueMeet = adjustments.meets[1];
  const queueRoot = `${expectedApiOrigin}/admin/clubs/${club}/interclub/registrations/${adjustments.id}/meets/${queueMeet.id}`;
  await page.goto(`/admin/interclub/registrations?season=${adjustments.id}&meet=${queueMeet.id}&step=availability`);
  const signupPanel = page.getByRole("region", { name: "Meet signup and substitute pool", exact: true });
  const openedSignup = page.waitForResponse(r => r.url() === `${queueRoot}/signup` && r.request().method() === "PUT");
  await signupPanel.getByRole("button", { name: "Open meet signup", exact: true }).click();
  const openedResponse = await openedSignup;
  expect(openedResponse.status()).toBe(200);
  const openedBoard: MeetSignupBoard = await openedResponse.json();
  const shareUrl = openedBoard.signup.url!;
  await expect(signupPanel.getByLabel("Share this meet signup link with your players", { exact: true })).toHaveValue(shareUrl);
  // Register directly from a vacancy, then review the declared gender separately.
  await signupPanel.getByRole("button", { name: "Add player to 3.5 women", exact: true }).click();
  const picker = signupPanel.getByRole("region", { name: "Choose player for 3.5 women", exact: true });
  const candidates = picker.getByRole("list", { name: "Eligible players by rating", exact: true });
  await expect(candidates).toBeVisible();
  const candidateText = await candidates.getByRole("button").allTextContents();
  const candidateRatings = candidateText.map(text => Number(text.match(/League rating ([0-9.]+)/)![1]));
  expect(candidateRatings).toEqual([...candidateRatings].sort((a, b) => b - a));
  expect(candidateRatings.every(rating => rating > 0 && rating < 4)).toBe(true);
  await candidates.getByRole("button").first().click();
  await picker.getByLabel("Gender", { exact: true }).selectOption("non_binary");
  await expect(picker.getByRole("status")).toContainText("An admin will review");
  // Signup mutations refresh the parent meet and remount this panel. Wait for the
  // new board before expanding Manage, or that refresh can close the form again.
  const addedBoardRefresh = page.waitForResponse(r => r.url() === `${queueRoot}/signup` && r.request().method() === "GET");
  const manualAdd = page.waitForResponse(r => r.url() === `${queueRoot}/signup/actions` && r.request().method() === "POST");
  await picker.getByRole("button", { name: "Submit for admin review", exact: true }).click();
  const manualResponse = await manualAdd;
  expect(manualResponse.status()).toBe(200);
  const manualBoard: MeetSignupBoard = await manualResponse.json();
  const reviewEntry = manualBoard.entries.find(entry => entry.declared_gender === "non_binary")!;
  expect(reviewEntry.placement).toBe("review");
  expect((await addedBoardRefresh).status()).toBe(200);
  await signupPanel.getByText(`Manage ${reviewEntry.name}`, { exact: true }).click();
  const reviewForm = signupPanel.getByRole("form", { name: `Review placement for ${reviewEntry.name}` });
  await expect(reviewForm).toBeVisible();
  const lineupPlace = reviewForm.getByLabel("Lineup place", { exact: true });
  await expect(lineupPlace).toBeVisible();
  await lineupPlace.selectOption("female");
  const reviewedBoardRefresh = page.waitForResponse(r => r.url() === `${queueRoot}/signup` && r.request().method() === "GET");
  const reviewed = page.waitForResponse(r => r.url() === `${queueRoot}/signup/actions` && r.request().method() === "POST");
  await reviewForm.getByRole("button", { name: "Approve placement", exact: true }).click();
  const reviewedResponse = await reviewed;
  expect(reviewedResponse.status()).toBe(200);
  const approved = ((await reviewedResponse.json()) as MeetSignupBoard).entries.find(entry => entry.id === reviewEntry.id)!;
  expect(approved.declared_gender).toBe("non_binary");
  expect(approved.reviewed_gender).toBe("female");
  expect(approved.placement).toBe("confirmed");
  expect((await reviewedBoardRefresh).status()).toBe(200);
  await expect(reviewForm).toHaveCount(0);
  await signupPanel.getByText(`Manage ${reviewEntry.name}`, { exact: true }).click();
  const removed = page.waitForResponse(r => r.url() === `${queueRoot}/signup/actions` && r.request().method() === "POST");
  await signupPanel.getByRole("button", { name: "Remove signup", exact: true }).click();
  expect((await removed).status()).toBe(200);
  const meetAnonymous = await browser.newContext({ baseURL: origin });
  await bootstrapStagingContext(meetAnonymous);
  const meetPage = await meetAnonymous.newPage();
  meetPage.on("pageerror", error => errors.push(error.message));
  await meetPage.goto(new URL(shareUrl).pathname);
  await meetPage.getByLabel("Find your name in the approved season pool", { exact: true }).fill(adjustments.browser_late_player);
  // Choosing a profile replaces the radio list with the selected profile card.
  await meetPage.getByRole("radio", { name: new RegExp(adjustments.browser_late_player) }).click();
  await meetPage.getByLabel("Gender", { exact: true }).selectOption("female");
  await expect(meetPage.getByText(/Your 3.35 league rating is below 3.5/)).toBeVisible();
  await meetPage.getByRole("checkbox", { name: /This is my profile and I want to play/ }).check();
  const shareId = new URL(shareUrl).pathname.split("/").at(-1)!;
  const joinUrl = `${expectedApiOrigin}/public/interclub-meet-signups/${shareId}`;
  const joined = meetPage.waitForResponse(r => r.url() === joinUrl && r.request().method() === "POST");
  await meetPage.getByRole("button", { name: "Sign me up for this meet", exact: true }).click();
  const joinedResponse = await joined;
  expect(joinedResponse.status()).toBe(200);
  const playUp: PrivateMeetSignup = await joinedResponse.json();
  expect(playUp.entry.priority).toBe("play_up");
  expect(playUp.entry.placement).toBe("waitlist");
  await expect(meetPage.getByRole("region", { name: "Your meet signup" })).toContainText("Substitute #1 · Playing up");

  const ratedPlayers = adjustments.players.filter((player: { club_id: string; division: string }) => player.club_id === club && player.division === "3.5");
  expect(ratedPlayers).toHaveLength(6);
  const joins = await Promise.all(ratedPlayers.map(async (player: { id: number; name: string }) => {
    const details = { player_id: player.id, name: player.name, division: "3.5", confirm_self: true, request_id: randomUUID() };
    const response = await meetAnonymous.request.post(joinUrl, { data: details });
    expect(response.status()).toBe(200);
    return { details, result: await response.json() as PrivateMeetSignup };
  }));
  const boardResponse = await meetAnonymous.request.get(joinUrl);
  expect(boardResponse.status()).toBe(200);
  const board: MeetSignupBoard = await boardResponse.json();
  expect(JSON.stringify(board)).not.toMatch(/token_nonce|manage_url|@example.invalid/);
  for (const gender of ["female", "male"]) {
    const ordered = board.entries.filter(entry => entry.gender === gender && entry.priority === "in_band");
    expect(ordered.map(entry => entry.placement)).toEqual(["confirmed", "confirmed", "waitlist"]);
    expect(ordered[2].queue_position).toBe(1);
  }
  expect(board.entries.find(entry => entry.id === playUp.entry.id)?.queue_position).toBe(2);
  const sameRetry = await meetAnonymous.request.post(joinUrl, { data: joins[0].details });
  expect((await sameRetry.json()).entry.manage_url).toBe(joins[0].result.entry.manage_url);
  const duplicate = await meetAnonymous.request.post(joinUrl, { data: { ...joins[0].details, request_id: randomUUID() } });
  expect((await duplicate.json()).duplicate).toBe(true);
  const firstWoman = board.entries.find(entry => entry.gender === "female" && entry.placement === "confirmed")!;
  const womanSignup = joins.find((join: { result: PrivateMeetSignup }) => join.result.entry.id === firstWoman.id)!.result;
  const nextWoman = board.entries.find(entry => entry.gender === "female" && entry.placement === "waitlist" && entry.priority === "in_band" && entry.queue_position === 1)!;
  expect(nextWoman.id).not.toBe(playUp.entry.id);
  const womanPage = await meetAnonymous.newPage();
  womanPage.on("pageerror", error => errors.push(error.message));
  const privateAddress = new URL(womanSignup.entry.manage_url!);
  await womanPage.goto(privateAddress.pathname + privateAddress.hash);
  await expect(womanPage.getByRole("region", { name: "Your meet signup" })).toContainText(firstWoman.name);
  expect(new URL(womanPage.url()).hash).toBe("");
  const withdrawal = womanPage.waitForResponse(r => r.url() === `${expectedApiOrigin}/public/interclub-meet-signups/withdraw` && r.request().method() === "POST");
  await womanPage.getByRole("button", { name: "Withdraw from this meet", exact: true }).click();
  const withdrawn = await withdrawal;
  expect(withdrawn.status()).toBe(200);
  const afterWithdrawal: PrivateMeetSignup = await withdrawn.json();
  expect(afterWithdrawal.entry.status).toBe("withdrawn");
  await expect(womanPage.getByRole("region", { name: "Your meet signup" })).toContainText("Withdrawn");
  expect(afterWithdrawal.entries.find(entry => entry.id === nextWoman.id)?.placement).toBe("confirmed");
  expect(afterWithdrawal.entries.find(entry => entry.id === playUp.entry.id)?.placement).toBe("waitlist");
  const lineupRead = await context.request.get(queueRoot, { headers: { Authorization: `Bearer ${user.token}` } });
  expect(lineupRead.status()).toBe(200);
  const autoTeam = (await lineupRead.json()).teams.find((team: { club_id: string; withdrawn: boolean }) => team.club_id === club && !team.withdrawn);
  expect(autoTeam.status).toBe("eligible");
  expect(autoTeam.roster.map((player: { name: string }) => player.name)).toContain(nextWoman.name);
  expect(autoTeam.roster.map((player: { name: string }) => player.name)).not.toContain(firstWoman.name);
  await meetPage.setViewportSize({ width: 390, height: 844 });
  await meetPage.getByRole("button", { name: "Refresh signup", exact: true }).click();
  await expect(meetPage.getByRole("region", { name: "Your meet signup" })).toContainText("Substitute #1 · Playing up");
  await meetPage.screenshot({ path: join(reportDir, "interclub-meet-signup-mobile.png"), fullPage: true });
  await signupPanel.getByRole("button", { name: "Refresh signups and lineups", exact: true }).click();
  await expect(signupPanel.getByRole("region", { name: "3.5 women", exact: true })).toContainText(nextWoman.name);
  await page.screenshot({ path: join(reportDir, "interclub-meet-signup-admin.png"), fullPage: true });
  await meetAnonymous.close();

  const anonymous = await browser.newContext({ baseURL: origin });
  await bootstrapStagingContext(anonymous);
  const publicPage = await anonymous.newPage();
  publicPage.on("pageerror", error => errors.push(error.message));
  await publicPage.goto(`/interclub/${official.id}`);
  await expect(publicPage.getByRole("heading",{ name: `Rehearsal ${state.run} full-season`, exact:true })).toBeVisible();
  await expect(publicPage.getByRole("heading", { name: "Overall Club Cup", exact: true })).toBeVisible();
  await expect(publicPage.getByText("Private revised note", { exact: false })).toHaveCount(0);
  await expect(publicPage.getByRole("tab", { name: "Overall standings", exact: true })).toHaveAttribute("aria-selected", "true");
  const cupTable = publicPage.getByRole("table", { name: "Club Cup standings", exact: true });
  await expect(cupTable).toBeVisible();
  await expect(cupTable.getByRole("columnheader")).toHaveText(["Place", "Club", "Points", "Meets", "Pairings won", "Games won", "Point difference"]);
  const publishedResponse = await publicPage.request.get(`${expectedApiOrigin}/public/interclub/${official.id}`);
  expect(publishedResponse.status()).toBe(200);
  const published: PublicLeague = await publishedResponse.json();
  const selectedClubName = published.document.clubs.find(row => row.id === club)!.name;
  const cupStats = published.club_cup!.standings.find(row => row.club_id === club)!;
  const cupRow = cupTable.getByRole("row").filter({ has: publicPage.getByRole("button", { name: `View results for ${selectedClubName}`, exact: true }) });
  await expect(cupRow.getByRole("cell")).toHaveText([`${cupStats.tied ? "T" : ""}${cupStats.position}`, String(cupStats.points), String(cupStats.meets_played), String(cupStats.pairings_won), String(cupStats.games_won), `${(cupStats.point_differential || 0) > 0 ? "+" : ""}${cupStats.point_differential}`]);
  await expect(publicPage.getByRole("heading", { name: "Meet schedule", exact: true })).not.toBeVisible();
  await expect(publicPage.getByRole("region", { name: "Browse match results", exact: true })).not.toBeVisible();
  await publicPage.screenshot({ path: join(reportDir, "interclub-overall-results.png"), fullPage: true });
  await publicPage.getByRole("tab", { name: "Results", exact: true }).click();
  const publicResults = publicPage.getByRole("region", { name: "Browse match results", exact: true });
  await expect(publicResults).toBeVisible();
  const clubFilter = publicResults.getByRole("combobox", { name: "Filter results by club", exact: true });
  await clubFilter.selectOption(club);
  const clubResults = published.document.competition_results!.filter(row => row.club_a === club || row.club_b === club);
  const expectedGames = clubResults.reduce((sum, row) => sum + row.pairings.reduce((n, pairing) => n + pairing.games.length, 0) + (row.tiebreak?.status === "completed" ? 1 : 0), 0);
  await expect(publicResults.locator("tr[data-result-game]")).toHaveCount(expectedGames);
  await expect(publicResults.getByText("Not needed — matchup decided 3–0", { exact: true })).toBeVisible();
  await expect(publicResults.locator("details")).toHaveCount(0);
  await expect(publicResults.locator("tr[data-result-game] td:nth-child(3) strong")).toHaveText(Array(expectedGames).fill(selectedClubName));
  await publicPage.screenshot({ path: join(reportDir, "interclub-club-results-table.png"), fullPage: false });
  const meetFilter = publicResults.getByRole("combobox", { name: "Filter results by meet", exact: true });
  await meetFilter.selectOption({ index: 1 });
  const playerFilter = publicResults.getByRole("combobox", { name: "Filter results by player", exact: true });
  await expect(playerFilter).toBeEnabled();
  await playerFilter.click();
  const selectedPlayer = publicResults.getByRole("listbox", { name: "Matching players", exact: true }).getByRole("option").filter({ hasNotText: /^All players$/ }).first();
  const selectedName = (await selectedPlayer.innerText()).split(" · ")[0];
  await selectedPlayer.click();
  await expect(publicResults.getByRole("status").first()).toContainText(`involving ${selectedName}`);
  const filteredGame = publicResults.locator("tr[data-result-game]").first();
  await expect(filteredGame).toBeVisible();
  await expect(filteredGame).toContainText(selectedName);
  await publicPage.setViewportSize({ width: 390, height: 844 });
  await publicPage.screenshot({ path: join(reportDir, "interclub-player-results-mobile.png"), fullPage: true });
  expect(await publicPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const scoreBounds = await filteredGame.locator("td").nth(2).boundingBox();
  expect(scoreBounds).not.toBeNull();
  expect(scoreBounds!.x).toBeGreaterThanOrEqual(0);
  expect(scoreBounds!.x + scoreBounds!.width).toBeLessThanOrEqual(390);
  await publicResults.getByRole("button", { name: "Clear filters", exact: true }).click();
  await publicPage.getByRole("tab", { name: "Schedule", exact: true }).click();
  await expect(publicPage.getByRole("heading", { name: "Meet schedule", exact: true })).toBeVisible();
  await expect(publicResults).not.toBeVisible();
  await publicPage.getByRole("link", { name: "View final results, champions, and trophies →", exact: true }).click();
  await expect(publicPage.getByRole("heading", { name: "Final season results", exact: true })).toBeVisible();
  await expect(publicPage.getByRole("region", { name: "Skill-level champions", exact: true }).getByRole("article")).toHaveCount(3);
  await expect(publicPage.getByRole("region", { name: "Final season results", exact: true })).toContainText(selectedClubName);
  await expect(publicPage.getByRole("table", { name: "Club Cup standings", exact: true })).toBeVisible();
  const recipientList = publicPage.getByRole("region", { name: "Player awards", exact: true });
  await recipientList.getByRole("combobox", { name: "Filter player awards by club", exact: true }).selectOption(club);
  const awardedPlayers = new Set(reviewedAwards.awards.filter((award: any) => award.club_id === club && award.recipient_type === "player").map((award: any) => award.entry_id));
  await expect(recipientList.getByRole("listitem")).toHaveCount(awardedPlayers.size);
  expect(await publicPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await publicPage.screenshot({ path: join(reportDir, "interclub-final-results-mobile.png"), fullPage: true });
  await publicPage.setViewportSize({ width: 1280, height: 900 });
  await publicPage.screenshot({ path: join(reportDir, "interclub-final-results.png"), fullPage: true });
  await publicPage.getByRole("link", { name: `${selectedClubName} trophy case`, exact: true }).click();
  await expect(publicPage.getByRole("heading", { name: "Club trophy case", exact: true })).toBeVisible();
  const clubAwardCount = reviewedAwards.awards.filter((award: any) => award.club_id === club && award.recipient_type === "club").length;
  await expect(publicPage.locator("[data-club-trophy]")).toHaveCount(clubAwardCount);
  await publicPage.getByRole("combobox", { name: "Filter club trophies", exact: true }).selectOption("club_cup_champion");
  await expect(publicPage.locator("[data-club-trophy]")).toHaveCount(1);
  await publicPage.screenshot({ path: join(reportDir, "interclub-club-trophy-case.png"), fullPage: true });
  await publicPage.goto(`/clubs/${club}/players/${official.browser_award_player}?section=trophies`);
  await expect(publicPage.getByRole("heading", { name: "Trophy case", exact: true })).toBeVisible();
  await expect(publicPage.locator('[data-testid="player-trophy"]').filter({ hasText: "Interclub Season Participant" })).toHaveCount(1);
  await expect(publicPage.locator('[data-testid="player-trophy"]').filter({ hasText: "Interclub Club Cup Champion" })).toHaveCount(1);
  await publicPage.screenshot({ path: join(reportDir, "interclub-player-trophy-case.png"), fullPage: true });
  await publicPage.getByRole("link", { name: "View final season results", exact: true }).first().click();
  await expect(publicPage.getByRole("heading", { name: "Final season results", exact: true })).toBeVisible();
  await publicPage.getByRole("link", { name: "View all match results", exact: true }).click();
  await expect(publicPage.getByRole("tab", { name: "Results", exact: true })).toHaveAttribute("aria-selected", "true");
  await publicPage.goto(`/interclub/signup/${official.signup[club].share_id}`);
  await expect(publicPage.getByRole("heading", { name: "Season registration has closed.", exact: true })).toBeVisible();
  await expect(publicPage.getByRole("button", { name: "Join the season player pool", exact: true, includeHidden: true })).toHaveCount(0);
  await publicPage.goto(`/interclub/signup/${signup.signup[club].share_id}`);
  const publicPlayerName = `Browser public new ${state.run}`;
  await publicPage.getByLabel("Your name", { exact: true }).fill(publicPlayerName);
  const publicNewPlayer = publicPage.getByRole("group", { name: "New player profile", exact: true });
  await expect(publicNewPlayer).toBeVisible();
  await publicNewPlayer.getByLabel("Starting JUPR", { exact: true }).fill("3.15");
  await publicNewPlayer.getByLabel("Gender", { exact: true }).selectOption("female");
  await publicPage.getByRole("textbox", { name: /^Email/ }).fill(`browser-${state.run}@example.invalid`);
  await publicPage.getByRole("checkbox",{ name:"3.5", exact:true }).check();
  await publicPage.getByRole("checkbox",{ name:/My club can email me invitations/ }).check();
  const publicCreated = publicPage.waitForResponse(r => r.url() === `${expectedApiOrigin}/public/interclub-signups/${signup.signup[club].share_id}` && r.request().method() === "POST");
  await publicPage.getByRole("button",{ name:"Join the season player pool", exact:true }).click();
  const publicCreatedResponse = await publicCreated;
  expect(publicCreatedResponse.status()).toBe(200);
  expect((await publicCreatedResponse.json()).status).toBe("registered");
  await expect(publicPage.getByRole("heading",{ name:"Your interest is registered", exact:true })).toBeVisible();
  await expect(publicPage.getByRole("link",{ name:"Manage my season signup", exact:true })).toHaveCount(1);
  await anonymous.close();
  const refreshedPool = page.waitForResponse(r => r.url() === signupPoolRoot && r.request().method() === "GET");
  await page.goto(`/admin/interclub/registrations?season=${signup.id}`);
  const refreshedPoolResponse = await refreshedPool;
  expect(refreshedPoolResponse.status()).toBe(200);
  const persistedMembers = (await refreshedPoolResponse.json()).members;
  const publicMember = expectLinkedPoolMember(persistedMembers, publicPlayerName, 3.15, "female");
  expect(publicMember.email).toBe(`browser-${state.run}@example.invalid`);
  expect(String(publicMember.player_id)).not.toBe(String(adminMember.player_id));
  expect(expectLinkedPoolMember(persistedMembers, adminPlayerName, 3.25, "female").id).toBe(adminMember.id);
  const publicPlayerRow = signupPool.getByRole("row").filter({ has: page.getByRole("rowheader").filter({ hasText: publicPlayerName }) });
  await expect(publicPlayerRow).toHaveCount(1);
  await expect(publicPlayerRow.getByRole("cell", { name: "3.15", exact: true }).first()).toBeVisible();
  expect(errors).toEqual([]);
  writeFileSync(join(reportDir,"interclub-season-awards-browser.json"),JSON.stringify({status:"passed",candidate_sha:state.sha,
    checks:["season_awards_review_and_publish","season_awards_reload","public_final_results","mobile_final_results","club_trophy_case","player_interclub_trophies","final_match_results_link"]},null,2));
  writeFileSync(join(reportDir,"interclub-browser.json"),JSON.stringify({ status:"passed",candidate_sha:state.sha,
    checks:["championship_three_zero_clinch","championship_correction_reopens_fourth","championship_tab_skips_fourth","championship_clinch_reload_and_approval","championship_clinch_pdf","completed_season_championship_panel","qualified_final_setup","mobile_championship_panel","meet_setup_without_duration","shared_meet_signup","play_up_waitlist","concurrent_signup_capacity","rating_band_fifo","signup_retry_identity","withdrawal_promotes_actual_roster","mobile_signup","paper_packet_pdf","six_game_ui_entry","dirty_navigation_lock","draft_reload","whole_meet_submission","organizer_approval","both_rating_streams","registration_phase_route_lock","admin_inline_player_creation","upcoming_meet_edit","add_meet_after_registration","late_inline_player_creation_without_notes","late_player_request_and_approval","guided_meet_lineup","eligible_player_filter","gender_composition","lineup_draft_preserved_on_pool_visit","anonymous_public_cup","overall_first_results","cup_stat_columns","all_club_games_visible","club_score_orientation","meet_club_player_filters","mobile_result_layout","compact_admin_results","closed_signup_readonly","anonymous_inline_player_signup","persisted_inline_profile_ratings","no_browser_exceptions"] },null,2));
});
