create table if not exists public.admin_role_assignments (
    id bigint generated by default as identity primary key,
    user_id uuid null,
    email text not null,
    role text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint admin_role_assignments_email_unique unique (email),
    constraint admin_role_assignments_role_check check (
        role in ('super_admin', 'club_owner', 'organizer', 'scorekeeper', 'read_only')
    )
);

create index if not exists admin_role_assignments_email_idx
    on public.admin_role_assignments (email);

create index if not exists admin_role_assignments_user_id_idx
    on public.admin_role_assignments (user_id);

create or replace function public.set_admin_role_assignments_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_admin_role_assignments_updated_at on public.admin_role_assignments;
create trigger trg_admin_role_assignments_updated_at
before update on public.admin_role_assignments
for each row
execute function public.set_admin_role_assignments_updated_at();
