create table if not exists public.admin_match_log_duplicate_resolutions (
    id bigint generated by default as identity primary key,
    club_id text not null,
    dup_key text not null,
    match_id_key text not null,
    match_ids jsonb not null,
    resolution text not null default 'no_issue',
    reason text,
    actor_email text not null,
    actor_role text not null,
    source_page text,
    is_active boolean not null default true,
    resolved_at timestamptz not null default now(),
    reopened_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint admin_match_log_duplicate_resolutions_resolution_check check (resolution in ('no_issue')),
    constraint admin_match_log_duplicate_resolutions_unique unique (club_id, dup_key, match_id_key)
);
create index if not exists admin_match_log_duplicate_resolutions_club_active_idx on public.admin_match_log_duplicate_resolutions (club_id, is_active);
create index if not exists admin_match_log_duplicate_resolutions_club_key_idx on public.admin_match_log_duplicate_resolutions (club_id, dup_key, match_id_key);
create or replace function public.set_admin_match_log_duplicate_resolutions_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;
drop trigger if exists trg_admin_match_log_duplicate_resolutions_updated_at on public.admin_match_log_duplicate_resolutions;
create trigger trg_admin_match_log_duplicate_resolutions_updated_at
before update on public.admin_match_log_duplicate_resolutions
for each row execute function public.set_admin_match_log_duplicate_resolutions_updated_at();
